### ISSUE TITLE
nacos config启动时的一个问题

### ISSUE THREAD

**Issue by dtssv** [alibaba/spring-cloud-alibaba#1049]
出现问题的是spring-cloud-starter-alibaba-nacos-config-2.1.0.RELEASE
我的配置是：
bootstrap.yml
```
spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        shared-dataids: order-provider.properties,order.properties
        refreshable-dataids: order.properties
        group: ORDER_GROUP
```
启动日志:
```
 c.a.c.n.c.NacosPropertySourceBuilder     : Loading nacos data, dataId: 'order.properties', group: 'DEFAULT_GROUP'
```
ApplicationRunner.java
```
    @Override
    public void run(ApplicationArguments args) throws Exception {
        nacosConfigProperties.configServiceInstance().addListener("order.properties", "ORDER_GROUP", new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String s) {
                Properties properties = new Properties();
                try {
                    properties.load(new StringReader(s));
                }catch (Exception e){
                    e.printStackTrace();
                }
            }
        });
    }
```
问题就是为什么我在配置文件配置的group好像没起作用
