### ISSUE TITLE
spring-cloud-alibaba不能使用ribbon的listOfServers，请问怎么进行feign的本地调试

### ISSUE THREAD

**Issue by JunRzz** [alibaba/spring-cloud-alibaba#1056]
我看了下NacosServerList中的getServers方法，是直接从nacos读取的配置，直接忽略了我在配置中设置的：
```

service-cloud-xxx:
  ribbon:
    listOfServers: localhost:8080
    ServerListRefreshInterval: 15000
```
这样对本地调试非常不友好啊
