### ISSUE TITLE
The configuration center common configuration cannot read the configuration set under the specified group

### ISSUE THREAD

**Issue by easylife94** [alibaba/spring-cloud-alibaba#1086]
**Nacos Config**

**Describe the bug**
The configuration center common configuration cannot read the configuration set under the specified group.

**To Reproduce**
1. Log on to nacos background create configuration 'spring-cloud-nacos-demo.yml' set up grouping 'DEMO'
2. Create an application setting 'bootstrap.yml'
```
spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        shared-dataids: spring-cloud-nacos-demo.yml
        refreshable-dataids: spring-cloud-nacos-demo.yml
        group: DEMO
```
3. Start the application
4. Log on to nacos background to view the monitoring query. There is no monitoring record
5. Create configuration 'spring-cloud-nacos-demo.yml' set up grouping 'DEFAULT_GROUP'
6. Look at the configuration listen query for the default group. There are listen records

**Additional context**
Windows7、Java8 、 Version 2.2.0.BUILD-SNAPSHORT
