### ISSUE TITLE
Nacos结合Ribbon进行负载时，当有多个服务需要负载时，会出现负载到错误服务的情况

### ISSUE THREAD

**Issue by superzhengzhe** [alibaba/spring-cloud-alibaba#1184]
1. 软件版本
SpringBoot版本： 2.0.1.RELEASE
SpringCloud版本：Finchley.RELEASE
AlibabaSpringCloud版本：2.0.1.RELEASE
NacosClient版本：1.1.4.RELEASE
2. 使用 Nacos+Ribbon
使用 com.alibaba.cloud.nacos.ribbon.NacosRule 作为自定义规则
现象：
如果有多个服务需要负载，会出现负载错误的情况
debug了一下，是因为 loadBalancer.getName() 得到了错误的服务名称

```
	@Override
	public Server choose(Object key) {
		try {
			String clusterName = this.nacosDiscoveryProperties.getClusterName();
			DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();
			String name = loadBalancer.getName();

			NamingService namingService = this.nacosDiscoveryProperties
					.namingServiceInstance();
			List<Instance> instances = namingService.selectInstances(name, true);
			......
		}
		catch (Exception e) {
			LOGGER.warn("NacosRule error", e);
			return null;
		}
	}
```

**Comment by fangjian0423** [comment]
Don't override the Nacos-Client version, it is included in Nacos Discovery Dependency.

Please provide a project that reproduces the issue if you also have the same problem after update Nacos-Client version.

**Comment by superzhengzhe** [comment]
场景：利用Spring Cloud Gateway转发请求到服务A和服务B，会负载到错误服务
项目一：Spring Cloud Gateway
1. Maven依赖
```
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <spring-boot.version>2.0.1.RELEASE</spring-boot.version>
        <spring-cloud.version>Finchley.RELEASE</spring-cloud.version>
        <alibaba-spring-cloud.version>2.0.1.RELEASE</alibaba-spring-cloud.version>
        <spring-cloud-gateway-core.version>2.0.2.RELEASE</spring-cloud-gateway-core.version>
        <fastjson.version>1.2.8</fastjson.version>
        <lombok.version>1.18.8</lombok.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${alibaba-spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-cloud-gateway-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gateway-core</artifactId>
            <version>${spring-cloud-gateway-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>

```
2. Nacos 配置
```
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacoshost:8848
      config:
        server-addr: nacoshost:8848
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'
```
3. Nacos上的gateway.yaml配置
```
management:
  security:
    enabled: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true              
          lowerCaseServiceId: true
      routes:
        - id: base-routes
          uri: lb://base
          predicates:
          - Path=/api/base/**
          filters:
          - StripPrefix=2
        - id: ecif-routes
          uri: lb://ecif
          predicates:
          - Path=/api/ecif/**
          filters:
          - StripPrefix=2

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 60000
```
4. 新建RibbonConfig
```
import com.alibaba.cloud.nacos.ribbon.NacosRule;
import com.netflix.loadbalancer.IRule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * @author zz
 * @date 2020/1/21 15:50
 */
@Configuration
public class RibbonConfig {

    @Bean
    public IRule getRibbonRule() {
        return new NacosRule();
    }

}
```
5. 通过gateway访问base服务和ecif服务的swagger文档
<1> 通过 http://localhost:8080/api/base/swagger-ui.html 访问base服务，此时转发正常
<2> 通过 http://localhost:8080/api/ecif/swagger-ui.html 访问ecif服务，此时转发正常
<3> 通过 http://localhost:8080/api/base/swagger-ui.html 再次访问base服务，此时转发异常，转发到了ecif服务
