### ISSUE TITLE
[Sentinel Zuul Gateway] NPE when `spring.cloud.sentinel.zuul.order` not configured

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#1213]
```yaml
spring.cloud.sentinel.zuul.order.pre: 2000
spring.cloud.sentinel.zuul.order.post: 500
spring.cloud.sentinel.zuul.order.error: -100
```

If none of them was configured, NPE occurs.
