### ISSUE TITLE
Sentinel-dashboard-1.7.1簇点链路不显示Web层接口

### ISSUE THREAD

**Issue by bjchen2** [alibaba/spring-cloud-alibaba#1304]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Describe what problem you have encountered**
我按照文档搭建了一个Spring Cloud-Alibaba项目，集成Sentinel。访问接口后，控制台只显示@SentinelResource 注解所修饰的方法，而Web埋点访问记录没有显示。
Translate:
I set up a Spring Cloud-Alibaba project according to the documentation to integrate Sentinel. After accessing the API, the console only displays the methods modified by the @SentinelResource annotation, but the API access records are not displayed.

Code：
```java
@RestController
public class Controller{
    @Autowired
    Service service;
    @GetMapping("/test/{id}")
    public Dto getOne(@PathVariable Integer id){
        return service.getById(id);
    }
}

@Service
public class Service {
    @SentinelResource(value = "getById")
    public Dto getById(Integer id){
        return new Dto();
    }
}
```
yaml:
```yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #指定Sentinel Web界面地址
        dashboard: localhost:8080
        port: 8719
  application:
    name: content
server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        include: "*"
```

我的理解，此时访问localhost:8010/test/1时，Sentinel控制台簇点链路应该显示“/test/1”和“getById”两个资源，然而事实上，只有“getById”被显示，显示情况如图
Translate:
In my opinion, when accessing localhost: 8010/test/1, the cluster point link of the Sentinel console should display the two resources '/test/1' and 'getById'. but in fact, only 'getById' is displayed.
![QQ图片20200331205925](https://user-images.githubusercontent.com/25131011/78029070-90cd1400-7392-11ea-815a-9df4cad63b82.png)

**Version:**
spring-cloud-alibaba : 2.2.0.RELEASE
spring-cloud: Hoxton.SR3
spring-boot: 2.2.5.RELEASE
System: Windows10

**Describe what information you have read**
在文档 https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-sentinel 中提到，“注：一般推荐将 @SentinelResource 注解加到服务实现上，而在 Web 层直接使用 Spring Cloud Alibaba 自带的 Web 埋点适配。”
