### ISSUE TITLE
Spring Cloud Alibaba 2.2.1.RELEASE  注册发现使用新建用户 会授权失败 403。主账户可以

### ISSUE THREAD

**Issue by niyaode** [alibaba/spring-cloud-alibaba#1372]
## 为什么 nacos 用户可以用，自己创建的用户会出现 403问题
github 图片不能正常打开，只能这样了
### 角色管理

角色名 | 用户名
---|---
ROLE_soft | xxxxx

### 权限管理
角色名 | 资源|动作
---|---|---
ROLE_soft | shop | 读写 (rw)

我在服务端配置了 用户名 密码，namespace 等 就是不行。 
我只依赖服务注册的包
```
//    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
```
```yml
  application:
    name: test-provider
  cloud:
    nacos:
      username: newUser
      password: newPassword
      discovery:
        server-addr: localhost:8848
        namespace: shop
```
服务端报错
```java
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([http://xxxx:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Apr 15 10:26:59 GMT+08:00 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>
```

**Comment by yanlinly** [comment]
ROLE_soft 这个角色有绑定resource权限吗？

**Comment by niyaode** [comment]
> ROLE_soft这个角色有绑定资源权限吗？

在哪绑定资源权限啊。在控制台什么位置

资源不是绑定命名空间吗

```
{"action":"w","resource":"shop:DEFAULT_GROUP:naming/admin-role-provider"}, user: {"globalAdmin":false,"token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2Z0U3lzdGVtIiwiZXhwIjoxNTg2OTM1NjEzfQ.OEY4FE23bkxaSQ6Cl7YG3Ip279zG3pFnTR5q97JSiEc","userName":"xxxxx"}
```

**Comment by nkorange** [comment]
你的用户名是xxxxx还是newUser？

**Comment by niyaode** [comment]
> 你的用户名是xxxxx还是newUser？
用户名是xxxxx  是我忽略的隐藏的，我不会把用户名填错。请不要把注意力放在这上面

**Comment by niyaode** [comment]
我使用docker搭建nacos集群，
```
NACOS_SERVERS=请忽略
MYSQL_SERVICE_HOST=请忽略
MYSQL_SERVICE_DB_NAME=请忽略
MYSQL_SERVICE_PORT=请忽略
MYSQL_SERVICE_USER=请忽略
MYSQL_SERVICE_PASSWORD=请忽略
NACOS_AUTH_ENABLE=true
```

```yml
version: "2"
services:
  nacos1:
    image: nacos/nacos-server:1.2.1
    container_name: nacos1
    networks:
      nacos_net:
        ipv4_address: 请忽略
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ../env/nacos-ip.env
    restart: on-failure
```
