### ISSUE TITLE
Always get changedGroupKeys in each longPulling, result in dead loop.

### ISSUE THREAD

**Issue by zcz3313** [alibaba/spring-cloud-alibaba#1445]
**Which Component**
Nacos Config, MySpringBootApplication(Spring Cloud Gateway, Version 2.0.9.RELEASE)

**Describe the bug**
always get changedGroupKeys in each longPulling, result in dead loop.

**To Reproduce**
1. create config file in nacos
```yaml
spring:
  clouod:
    gateway:
      dicovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - Path='/api/'+serviceId+'/**' 
```

2. start spring boot application
3. see log
4.modify '/api/'+serviceId+'/**' -> '/open-api/'+serviceId+'/**'
5.see log
6.modify  '/open-api/'+serviceId+'/**' -> '/api/'+serviceId+'/**'
7.see log (probably see the dead loop log)

**Expected behavior**
produce one log record in each modification action

**Screenshots**
![image](https://user-images.githubusercontent.com/8746495/81519295-51232000-9373-11ea-979e-2e355fc68f01.png)

**Additional context**
Linux  、Java8 、 Version 2.1.2.RELEASE
