### ISSUE TITLE
Nacos 使用 gateway 无法发现自定义 group  与namespace的服务

### ISSUE THREAD

**Issue by NineSwordsMonster** [alibaba/spring-cloud-alibaba#1480]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos

**Describe the bug**

**To Reproduce**
1. 注册服务与消费者
```yaml
spring:
  application:
    name: my-service

# common config
  cloud:
    # nacosdiscovery config
    nacos:
      discovery:
        server-addr: 192.168.31.148:8848
        username: nacos
        password: nacos

        namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
        group: dev
        service: my-service
        cluster-name: c-1
```
2. 开启gateway负载

```yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
```
```java
    @Bean
    @Scope(value = "prototype")
    public IRule loadBalanceRule() {
        return new NacosRule();
    }
```

3. 访问地址
4. 无法找到在线服务

**Expected behavior**
可自动发现并转发

**Screenshots**
![image](https://user-images.githubusercontent.com/10054584/82854336-b4e44600-9f3a-11ea-9a67-0d9df2595a6e.png)

**Additional context**
MacOS  、Java8 、 
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
