### ISSUE TITLE
No topic route info in name server for the topic: RMQ_SYS_TRACE_TOPIC

### ISSUE THREAD

**Issue by pengliangs** [alibaba/spring-cloud-alibaba#1513]
在使用阿里云 `消息队列 for Apache RocketMQ` 时发现消息被消费但是查询 `消息轨迹` 始终显示 `尚未消费`  在日志中发现如下错误：

No topic route info in name server for the topic: RMQ_SYS_TRACE_TOPIC

---

When using Alibaba Cloud's "Message Queuing for Apache RocketMQ", it was found that the message was consumed but the query "Message Trace" always shows "Not yet consumed". The following errors were found in the log:

No topic route info in name server for the topic: RMQ_SYS_TRACE_TOPIC

**Configuration information**

```
spring:
  cloud:
    stream:
      bindings:
        TEST_ONE_INPUT:
          destination: TEST_TOPIC
          group: xxx%GID_TEST_ONE
        TEST_TWO_INPUT:
          destination: TEST_TOPIC
          group: xxx%GID_TEST_TWO
          
      rocketmq:
        bindings:
          TEST_ONE_INPUT:
            consumer:
              tags: tag1
          TEST_TWO_INPUT:
            consumer:
              tags: tag2
              
---

spring:
  cloud:
    stream:
      bindings:
        APP_SOURCE_OUTPUT:
          destination: TEST_TOPIC
      rocketmq:
        bindings:
          APP_SOURCE_OUTPUT:
            producer:
              group: xxx%GID_PRODUCER_TEST_GROUP
```
