### ISSUE TITLE
1.5.1 版本不支持nacos认证吗

### ISSUE THREAD

**Issue by yugj** [alibaba/spring-cloud-alibaba#1609]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
 Nacos 

**Describe what problem you have encountered**
```
spring:
  cloud:
    nacos:
      discovery:
        username: user
        password: pass
```
有个老项目有Springboot1.5 的，发现使用1.5.1版本，集成进来的nacos-cient 1.1.1 访问配置和注册都是403
请问是版本问题吗？ 有没有什么方式兼容的？

**Describe what information you have read**
https://nacos.io/zh-cn/index.html
