### ISSUE TITLE
Nacos as Service Discovery Center started at port 8080 despite configuration

### ISSUE THREAD

**Issue by michaelfyc** [alibaba/spring-cloud-alibaba#1761]
My Nacos Server Version: 1.3.2
Spring Cloud Alibaba Version: 2.2.1 RELEASE

I'm using Nacos as a standalone service-discovery center. I followed what the official documentation says and made little adjustments.. Here's my `application.yml` for server module.

```
server:
  port: 9555
spring:
  application:
    name: SERVICE-NACOS-SERVER
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: http://localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
```
Nevertheless, when I tried to start my hello-world project, it started at port 8080 instead of port 9555 that I specified in the file. Nacos service list was empty too.  Passing server.port as arguments works, however. I wonder why this is happening...
