### ISSUE TITLE
I set nacos datasource at sentinel config，but restart the micro service，the rule will missing

### ISSUE THREAD

**Issue by felixyin** [alibaba/spring-cloud-alibaba#1883]
I set flow rule at sentinel console，and config the Nacos json，start micro service can read the rule，bug I can't save setting to nacos mysql use the sentinel console。
我是初学者，疑问是：配置仅仅只能从nacos配置中心“通知”下去吗？不能通过sentinel直接修改保存到nacos吗？
官方文档：https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#动态数据源支持
配置参考的是：https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties

I can't find the reason，jdk version 1.8, pom compile level 1.8

the dependency versions:
```
  <spring.boot.version>2.2.2.RELEASE</spring.boot.version>
  <spring.cloud.version>Hoxton.SR1</spring.cloud.version>
  <spring.cloud.alibaba.version>2.1.1.RELEASE</spring.cloud.alibaba.version>
```

the yml：

```
server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      eager: true
      transport:
        # sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
      # 流控规则持久化到nacos
      datasource:
        ds1: # fixme 始终无法持久化，??????????????????????????????????????????????????????????????
          nacos:
            server-addr: "localhost:8848"
            username: nacos
            password: nacos
#            namespace: public
            data-id: sentinel
#            group-id: DEFAULT_GROUP
            data-type: json
#            converter-class: com.qtrj.scali.JsonFlowRuleListConverter
            rule-type: flow
      #        ds2: # 这个可以实现flow配置的加载
      #          file:
      #            file: "classpath: flowrule.json"
      #            data-type: json
      #            rule-type: flow
      http-method-specify: false
      filter:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

```

the dependencies:
```
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <!--     sentinel-datasource-nacos 后续持久化用   -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
```
