### ISSUE TITLE
springCloudAlibaba2.2.4+dubbo2.7.8+nacos环境下，重启服务提供者或先启动服务消费出现No provider available from registry localhost:9090

### ISSUE THREAD

**Issue by tianxinjs** [alibaba/spring-cloud-alibaba#1936]
org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:9090 for service com.**.service.* on consumer 192.168.56.1 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:74)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:292)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:257)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)

**Comment by theonefx** [comment]
能否提供更多的细节，以便于我们定位该问题

**Comment by myr666233** [comment]
消费者yml配置dubbo.consumer.check=false

**Comment by theonefx** [comment]
> 消费者yml配置dubbo.consumer.check=false

该配置项，是为了保证应用在启动时，所有依赖的提供者都在线，从而保证上线后功能全部可用。
不过，issue 中提到的 ”重启服务提供者“ 的操作，还需要 @tianxinjs 补充一下细节，以目前的信息无法判断细节

**Comment by mhxy2018** [comment]
我也遇到了，看到版本更新说2.2.5.RC1修复了部分的dubbo注册问题以为ok了，更新到2.2.5.RC2也还是不行，dubbo依赖和nacos依赖跟随alibaba-cloud版本
Nacos服务版本：1.4.0
springCloudAlibaba：2.2.5.RC2
springboot：2.3.6.RELEASE
nacos-client：1.4.1（alibaba-cloud）
dubbo：2.7.8（alibaba-cloud）
此外，我在springboot使用dubbo注册到nacos是可以的，
Nacos服务版本：1.4.0
springboot：2.3.6.RELEASE
nacos-client：1.4.0
dubbo：2.7.8

**Comment by theonefx** [comment]
> 我也遇到了，看到版本更新说2.2.5.RC1修复了部分的dubbo注册问题以为ok了，更新到2.2.5.RC2也还是不行，dubbo依赖和nacos依赖跟随alibaba-cloud版本
> Nacos服务版本：1.4.0
> springCloudAlibaba：2.2.5.RC2
> springboot：2.3.6.RELEASE
> nacos-client：1.4.1（alibaba-cloud）
> dubbo：2.7.8（alibaba-cloud）
> 此外，我在springboot使用dubbo注册到nacos是可以的，
> Nacos服务版本：1.4.0
> springboot：2.3.6.RELEASE
> nacos-client：1.4.0
> dubbo：2.7.8

2.2.5.RC2 是修复了部分 dubbo + SCA 的问题，不过刚才确实发现还有遗留问题未处理。目前可以确定的是一些顺序问题导致的规则推送失败。最新的代码已经在等待合并中了，如果着急的话，也欢迎直接从我的分支里拉取代码确认一下，以下是分支的地址：
https://github.com/theonefx/spring-cloud-alibaba/tree/endpoints

**Comment by TYtangyi** [comment]
springCloudAlibaba2.2.3+2.7.8的dubbo，nacos本地环境最近也出现这种问题
org.apache.dubbo.rpc.RpcException: No provider available from registry nacos.*:80 for service * on consumer 192.168.26.29 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:74)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:292)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:257)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker.doInvoke(ZoneAwareClusterInvoker.java:103)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:260)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)

**Comment by theonefx** [comment]
请升级到 2.2.5.RELEASE

**Comment by theonefx** [comment]
> springCloudAlibaba2.2.3+2.7.8的dubbo，nacos本地环境最近也出现这种问题
> org.apache.dubbo.rpc.RpcException: No provider available from registry nacos.*:80 for service * on consumer 192.168.26.29 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
> at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
> at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:74)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:292)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:257)
> at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
> at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
> at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
> at org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker.doInvoke(ZoneAwareClusterInvoker.java:103)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:260)
> at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
> at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
> at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)

请升级到 2.2.5.RELEASE

**Comment by theonefx** [comment]
问题应该已经解决了；此issue先关闭了，如果还有问题，另提issue再继续；
The issue is closed first, if there are any problems, please raise another issue continuing;

**Comment by cxdhefei** [comment]
Spring Cloud Hoxton.SR8
Spring Cloud Alibaba 2.2.5.RELEASE
Spring Boot 2.3.2.RELEASE
nacos-server 1.4.0
dubbo 2.7.8  问题依旧，日常开发中，服务重启后，还是会经常出现找不到提供者问题，报错：
```
2021-03-03 17:52:15.401 ERROR [http-nio-2130-exec-2] com.xy.sdx.common.web.handler.GlobalExceptionHandler:123 [2635a530-7c06-11eb-95f5-191adff1aaa3] No provider available from registry localhost:9090 for service com.xy.sdx.admin.api.RpcUserService on consumer 192.168.13.1 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:9090 for service com.xy.sdx.admin.api.RpcUserService on consumer 192.168.13.1 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:74)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:292)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:257)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
```
提供者配置：
```
dubbo:
  scan:
    base-packages: com.xy.sdx.branch
  application:
    name: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: 20040
  registry:
    id: ${spring.application.name}
    address: spring-cloud://localhost
  #  config-center:
  #    address: nacos://localhost:8848
  #  metadata-report:
  #    address: nacos://localhost:8848
  cloud:
    subscribed-services: ''
  consumer:
    check: false
    timeout: 60000
    retries: 0
  provider:
    filter: -exception
```
消费者配置：
```
dubbo:
  scan:
    base-packages: com.xy.sdx.uaa
  application:
    name: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: 21030
  registry:
    id: ${spring.application.name}
    address: spring-cloud://localhost
  #  config-center:
  #    address: nacos://localhost:8848
  #  metadata-report:
  #    address: nacos://localhost:8848
  cloud:
    subscribed-services: sdx-admin,sdx-branch
  consumer:
    check: false
    timeout: 60000
    retries: 0
```
