### ISSUE TITLE
Dubbo cannot find the provider

### ISSUE THREAD

**Issue by cqyisbug** [alibaba/spring-cloud-alibaba#1947]
**Which Component**
Dubbo

**Describe the bug**
When the bean `SimpleAsyncTaskExecutor ` is defined

 the Dubbo consumer cannot find the service provider

**To Reproduce**
1. define the bean
```java
@Bean(name = "applicationEventMulticaster")
    public ApplicationEventMulticaster simpleApplicationEventMulticaster() {
        SimpleApplicationEventMulticaster eventMulticaster
                = new SimpleApplicationEventMulticaster();
        eventMulticaster.setTaskExecutor(new SimpleAsyncTaskExecutor());
        return eventMulticaster;
    }
```
2. specify the protocol，it is good when using `nacos://`
```yml
dubbo:
  registry:
    address: spring-cloud://${spring.cloud.nacos.discovery.server-addr}
```
3.run

**Additional context**
JDK:1.8
Nacos 1.4.1
SpringBoot：2.2.5.RELEASE
SpringCloud：Hoxton.SR8
SpringCloudAlibaba: 2.2.5.RC2
