### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery:2.1.1.RELEASE not support password

### ISSUE THREAD

**Issue by hegphegp** [alibaba/spring-cloud-alibaba#2043]
* spring-cloud-starter-alibaba-nacos-discovery:2.1.1.RELEASE not support password，I config password in the application.yml, but it's not work.

```
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        namespace: public
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
```

![image](https://user-images.githubusercontent.com/26202719/115150314-5cf68680-a09a-11eb-8cd8-2862818c63cc.png)
