### ISSUE TITLE
stream-rocketmq Grouped consumption is not load balanced

### ISSUE THREAD

**Issue by yl-yue** [alibaba/spring-cloud-alibaba#2066]
## First question
stream-rocketmq 分组消费不负载均衡。
Grouped consumption is not load balanced.

## Second question
不支持 [spring_cloud_function](https://docs.spring.io/spring-cloud-stream/docs/3.0.12.RELEASE/reference/html/spring-cloud-stream.html#spring_cloud_function).
Does not support [spring_cloud_function](https://docs.spring.io/spring-cloud-stream/docs/3.0.12.RELEASE/reference/html/spring-cloud-stream.html#spring_cloud_function)

**Comment by zkzlx** [comment]
please provide more information

**Comment by yl-yue** [comment]
## 关于分组消费时，多实例情况不负载均衡
> ## With regard to grouped consumption, the multi-instance case is not load-balanced
rocketmq:V4_7_0
springcloudalibaba 2.2.5.RELEASE
![image](https://user-images.githubusercontent.com/39790401/117596464-03074f00-b176-11eb-996d-4199f3900b1f.png)
![image](https://user-images.githubusercontent.com/39790401/117596485-10243e00-b176-11eb-84cb-607c61de6646.png)
如上图所示，rocketmq中已识别分组中有两位消费者，但实际上永远只有一个实例在工作。
springcloudstream配置如下：
> As shown in the figure above, RocketMQ has identified two consumers in the group, but in reality only one instance is always working.
> Spring CloudStream is configured as follows:
```yml
spring:
  cloud:
    stream:
      bindings:
        canalInputEsSyncSsc:
#          consumer:
#            concurrency: 20
          destination: es_sync_ssc
          content-type: application/json
          group: es_sync_consumer_ssc
```
```java
    @StreamListener("canalInputEsSyncSsc")
    public void canalInputEsSyncSsc(String binlogStr) {
```

## 关于不支持springcloudfunction方式
即：只需使用`java.util.function.Consumer`即可定义一个消费者，这是Spring Cloud Stream v3推荐的方式，而`@StreamListener`已经过时了
> ## About not supporting the Spring CloudFunction mode
> just use `java.util.function.Consumer` can define a Consumer, it is Spring Cloud Stream v3 recommended way, while `@StreamListener` is outdated
```java
	@Bean
	public Consumer<String> sink() {
		return System.out::println;
	}
```
