### ISSUE TITLE
指定版本号

### ISSUE THREAD

**Issue by HuShao96** [alibaba/spring-cloud-alibaba#2084]
项目a是消费者。指定消费提供者version：1.0.0；@DubboReference(version = "1.0.0")
项目b是提供者，分别启动两个服务
version：1.0.0:
```
server:
  port: 6201
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '1.0.0'
spring:
  application:
    name: flow-process-center
```
version:2.0.0:
```
server:
  port: 6202
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '2.0.0'
spring:
  application:
    name: flow-process-center
```
；
但是项目a还是会轮训调用项目b的两个不同版本的服务；
spring cloud alibaba 2021.1+dubbo;
![image](https://user-images.githubusercontent.com/26806329/118955265-1d6cd400-b991-11eb-97a5-5fdb984dcfe9.png)
