### ISSUE TITLE
关于使用spring-cloud-starter-stream-rocketmq 2021.1 版本中的Spring Cloud Stream新特性

### ISSUE THREAD

**Issue by likedeke** [alibaba/spring-cloud-alibaba#2174]
1.我的依赖
```xml
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config-server</artifactId>
	<version>2021.1</version>
</dependency>
```

2.producer
```java
/**
 * 注册producer：test-out-0
 *
 * @return {@link Supplier<String>}
 */
@Bean
public Supplier<String> test() {
    return () -> {
        String s= UUID.fastUUID().toString()
        System.out.println("发送消息：" + s);
        return s;
    };
}

```

3.comsumer
```java

/**
 * 注册consumer：test-in-0
 *
 * @return {@link Consumer<String>}
 */
@Bean
public Consumer<String> test() {
    return (s) -> {
        System.out.println("收到消息：" + s);
    };
}
```

4.问题
启动后会自动一直发信息，这种咋办？
prodcuer
![image](https://user-images.githubusercontent.com/65269574/126036566-5320883f-414d-47e0-a893-dae2dd62f973.png)

consumer

![image](https://user-images.githubusercontent.com/65269574/126036609-bc12216c-4632-4093-ad2a-15a9e440a796.png)

**Comment by likedeke** [comment]
配置
```yml
spring:
  cloud:
    stream:
      function:
        definition: test
      bindings:
        test-out-0:
          destination: test-topic
          content-type: application/json
        test-in-0:
          destination: test-topic
          content-type: application/json
          group: test-group
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876 # RocketMQ Namesrv 地址
          grou: test
        bindings:
          test-out-0:
            producer:
              group: test-group
              sync: true
          test-in-0:
            consumer:
              group: test-group
              orderly: true
```
