### ISSUE TITLE
nacos中配置文件修改后（比如修改上传文件的大小配置），控制台已经监测到，但是需要重启项目才能生效，是哪里出了问题呢

### ISSUE THREAD

**Issue by g0123** [alibaba/spring-cloud-alibaba#2206]
<spring-boot.version>2.3.7.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR9</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>

**Comment by yuhuangbin** [comment]
怎么使用的呢？可以参考一下example工程

https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example

**Comment by g0123** [comment]
程序配置项：
![图片](https://user-images.githubusercontent.com/31271129/128470957-e795599e-c0b9-438d-97fa-9ad28b5603fb.png)
nacos配置：
![图片](https://user-images.githubusercontent.com/31271129/128471129-6d3c72ec-4959-4cbf-b770-b9b0f8df2dda.png)
修改了上传文件的参数后，再次进行上传，限制没有生效。没有用到@RefreshScope，但nacos是默认刷新的呢

**Comment by yuhuangbin** [comment]
```yaml
spring:
  cloud:
    nacos:
      config:
        shared-configs:
         - dataId: xxx.yaml
           refresh: true
```

refresh = true 开启一下。
