### ISSUE TITLE
nacos-config从2.1.1.RELEASE升级到2020.0.3以后，从server获取到的配置不会打印到控制台了

### ISSUE THREAD

**Issue by zqr95518** [alibaba/spring-cloud-alibaba#2237]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-alibaba-nacos-config:2020.0.3

**Is your feature request related to a problem? Please describe.**
从2.1.1.RELEASE升级到2020.0.3以后，从server获取到的配置不会打印到控制台了。
After upgrading from 2.1.1.RELEASE to 2020.0.3, the configuration obtained from the server will not be printed to the console.

**Describe the solution you'd like**
启动的时候打印从server获取到的配置。
Print the configuration obtained from the server at startup.

**Describe alternatives you've considered**
没有相关打印。
No related printing.

**Additional context**
Add any other context or screenshots about the feature request

**Comment by zqr95518** [comment]
发现根本没有获取到config
```
spring:
  application:
    name: questionnaire
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yaml
        extension-configs:
          - dataId: default.yaml
            group: DEFAULT_GROUP
            refresh: true
```
