### ISSUE TITLE
How can I verify that Sentinel Feign Circuit Breaker Example takes effect?

### ISSUE THREAD

**Issue by icuxika** [alibaba/spring-cloud-alibaba#2405]
### Doc
```
Verify that the default feign client takes effect. First visit http:localhost/test/default/false 2 times and then visit http:localhost/test/default/true, the circuit breaker is open

Verify that the specified feign client takes effect. First visit http:localhost/test/feign/false 2 times and then visit http:localhost/test/feign/true, the circuit breaker is open

Verify that the specified method of feign client takes effect. First visit http://localhost/test/feignMethod/false 2 times and then visit http://localhost/test/feignMethod/true, the circuit breaker is open
```
### Test
I jsut get "ok" at the third time. Whether the program enters fallback is considered successful？

**Comment by DanielLiu1123** [comment]
The config in example, you should occur 2 times fallback in ***1 second***, then the 3rd request occur fallback means it works.

**Comment by icuxika** [comment]
Thank you. I got it. But I found that the `feign.sentinel.rules` does not work when I replace `spring-cloud-circuitbreaker-sentinel` 
 with `spring-cloud-starter-alibaba-sentinel` and set  `feign.sentinel.enable` value true. I can get the same reuslt in the example `Sentinel Feign Example` when I copy the sentinel config to the consumer config file.

**Comment by DanielLiu1123** [comment]
try `feign.circuitbreaker.enabled=true`

**Comment by icuxika** [comment]
`feign.circuitbreaker.enabled=true` has always existed. The request will enter fallback code when it occur Exception, but the provider service will not be blocked in 15s(timeWindow).


```
feign:
  circuitbreaker:
    enabled: true
  sentinel:
    enabled: true
    default-rule: default
    rules:
      # global feign client
      default:
        - grade: 2
          count: 1
          timeWindow: 15
          statIntervalMs: 3000
          minRequestAmount: 1
      # specific feign client
      user:
        - grade: 2
          count: 1
          timeWindow: 15
          statIntervalMs: 1000
          minRequestAmount: 1
      # specific feign client single method
      "[user#feignMethod(boolean)]":
        - grade: 2
          count: 1
          timeWindow: 10
          statIntervalMs: 1000
          minRequestAmount: 1
```
```
<!--        <dependency>-->
<!--            <groupId>com.alibaba.cloud</groupId>-->
<!--            <artifactId>spring-cloud-circuitbreaker-sentinel</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
```
If I set `feign.sentinel.enable=false` , the request will get correct result, otherwise the circuit breaker will never be open. More, If you try `feign.sentinel.enable=true` in `Sentinel Feign Example`, it's easily to see that the fallback code prints `consumer-fallback-default-strnull` (the circuit breaker is open) while `feign.sentinel.enable` not exist or it's value is false and it will always print `consumer-fallback-default-str[500] during [GET] to [http://service-provider/echo/sss] [EchoService#echo(String)].......................................................................` (the circuit breaker is always closed) while `feign.sentinel.enable=true` exists. The fallback works and but the service does not be blocked in the time window.
