### ISSUE TITLE
nacos 2.0.4 alibaba.cloud 2021.1 boot 2.6.4 配置不能自动刷新

### ISSUE THREAD

**Issue by 274574162** [alibaba/spring-cloud-alibaba#2434]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

![image](https://user-images.githubusercontent.com/39609367/156750429-5f1c45e1-0913-4611-bda7-991e7e29f07a.png)
![image](https://user-images.githubusercontent.com/39609367/156750475-e1dca7ae-6348-4f6e-9ea9-b6ad8bc35c81.png)
![image](https://user-images.githubusercontent.com/39609367/156750548-eb25a49a-f1d1-402d-8cab-00dc92ab454c.png)
能获取到配置,但是不能自动刷新

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by DanielLiu1123** [comment]
Like this configuration 
```yaml
spring:
  cloud:
    nacos:
      config:
        shared-configs:
          - dataId: xxx
            group: group_1
            refresh: true
          - dataId: xxxx
            group: group_2
            refresh: true
```

Please try to follow the [version convention](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).
