### ISSUE TITLE
2021.0.1.0版本spring.config.import配置文件优先级的问题

### ISSUE THREAD

**Issue by imyxiao** [alibaba/spring-cloud-alibaba#2455]
**Which Component**

按照[Spring Cloud Alibaba 2021.0.1.0 升级指南](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc)升级版本

遵循[毕业版本依赖关系(推荐使用)](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E#%E6%AF%95%E4%B8%9A%E7%89%88%E6%9C%AC%E4%BE%9D%E8%B5%96%E5%85%B3%E7%B3%BB%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8)

- spring boot 2.6.3
- spring cloud 2021.0.1
- spring cloud alibaba 2021.0.1.0

`nacos server`版本为`2.0.4`

**Describe what problem you have encountered**

本地`application.yml` `application-dev.yml`配置如下：

`application.yml`

```yaml
spring:
  application:
    name: bike
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        failure-tolerance-enabled: true
  config:
    import:
      - nacos:share.yaml?refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?refreshEnabled=true

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: nacos.xxxxxx.com:8848
      config:
        server-addr: nacos.xxxxxx.com:8848
```

`application-dev.yml`:

```yaml
test: local...
```

nacos上配置了`bike.yaml`:

```yaml
test: nacos...
```

我期望的结果是

nacos上的`bike.yaml`优化级比本地的`application-dev.yml`高，`test`值为`nacos...`，之前使用bootstrap引入配置就是如此。

但实际测试的结果

`test`值为`local...`

这样导致我无法在nacos动态修改`application-{profile}.yml`的配置

**Comment by yuhuangbin** [comment]
使用 `spring.config.import` 的优先级就是靠后的配置优先，会覆盖之前的配置
```yaml
spring:
  config:
    import:
      - optional:nacos:test1.yaml
      - optional:nacos:test2.yaml
```

配置优先级为 `test1.yaml ` <  ` test2.yaml`
