### ISSUE TITLE
spring.cloud.config.file-extension is invalid 

### ISSUE THREAD

**Issue by shentuzhigang** [alibaba/spring-cloud-alibaba#2462]
**Which Component**
按照[Spring Cloud Alibaba 2021.0.1.0 升级指南](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc)升级版本

遵循[毕业版本依赖关系(推荐使用)](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E#%E6%AF%95%E4%B8%9A%E7%89%88%E6%9C%AC%E4%BE%9D%E8%B5%96%E5%85%B3%E7%B3%BB%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8)

spring boot 2.6.3
spring cloud 2021.0.1
spring cloud alibaba 2021.0.1.0
nacos server版本为2.0.4

[Spring Cloud Alibaba 2021.0.1.0 升级指南](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc)

```
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: myzstu
        file-extension: yaml
```
**Describe what problem you have encountered**
`spring.cloud.config.file-extension` is invalid 
```
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation, group=DEFAULT_GROUP
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation.properties, group=DEFAULT_GROUP
```
**Describe what information you have read**
have new config to replace this?

**Comment by DanielLiu1123** [comment]
Show your pom and configuration files.

**Comment by shentuzhigang** [comment]
> Show your pom and configuration files.

I am sure to use  [Spring Cloud Alibaba 2021.0.1.0 升级指南](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc)升级版本

 configuration files.
```
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: myzstu
        file-extension: yaml
```

**Comment by DanielLiu1123** [comment]
1. Are you using "import" way or "bootstrap" way ?
2. If using "import" way, please show the "spring.config.import" entry.

BTW, it's better if you can provide a minimal demo in your repo.

**Comment by shentuzhigang** [comment]
> 1. Are you using "import" way or "bootstrap" way ?
> 2. If using "import" way, please show the "spring.config.import" entry.
> 
> BTW, it's better if you can provide a minimal demo in your repo.

You don't seem to understand what I mean. In the 2021.1 version, `spring.cloud.config.file-extension` can specify the suffix of the configuration file that is pulled by default, which can be viewed in
![image](https://user-images.githubusercontent.com/46020123/158816256-e42a5b08-d91f-477d-9a97-9540729feec3.png)

That is to say,
If this configuration
```
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: myzstu
        file-extension: yaml
```
 the log in the issue body
```
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation, group=DEFAULT_GROUP
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation.properties, group=DEFAULT_GROUP
```
should be
```
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation, group=DEFAULT_GROUP
2022-03-15 23:11:02.137  INFO 90740 --- [  restartedMain] c.a.c.n.refresh.NacosContextRefresher    : listening config: dataId=comprehensive-evaluation.yaml, group=DEFAULT_GROUP
```

caution listening config: dataId 

where comprehensive-evaluation is the application name
