### ISSUE TITLE
how to config muti-env,muti-files?

### ISSUE THREAD

**Issue by abelzhyb** [alibaba/spring-cloud-alibaba#2506]
there are  5 files:
在nacos中有以下5个配置文件
scores-prod.yaml
scores-test.yaml
scores-common.yaml
scores-port.yaml
logback-spring.yml

I hope nacos load scores-common.yaml、scores-port.yaml、logback-spring.yml and one of scores-prod.yaml,scores-test.yaml at he same time，how to config bootstrap.yaml？
在bootstrap.yaml应该如何配置，才能同时加载scores-common.yaml、scores-port.yaml、logback-spring.yml以及按照prod,test选择性加载scores-prod.yaml,scores-test.yaml其中之一？应该用shared-configs，还是extension-configs？

**Comment by DanielLiu1123** [comment]
使用共享配置（shared-configs）还是扩展配置（extension-configs）需要自行判断你的配置类型，我猜测  `scores-common.yaml`，`logback-spring.yml` 应该算是共享配置。

如果你是使用 2021.0.1.0 以下版本：
```yaml
# bootstrap.yml
spring:
  application:
    name: scores
  profiles:
    active: test
  cloud:
    nacos:
      config:
        file-extension: yaml
        shared-configs:
          - dataId: scores-common.yaml
          - dataId: logback-spring.yml
```

如果你是使用 2021.0.1.0 及以上版本：
```yaml
# application.yml
spring:
  application:
    name: scores
  profiles:
    active: test
  config:
    import: 
      - optional:nacos:scores-common.yaml
      - optional:nacos:logback-spring.yml
---
spring:
  config:
    activate:
      on-profile: test
    import: optional:nacos:scores-test.yaml
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:nacos:scores-prod.yaml
```
