### ISSUE TITLE
nacos-config-2.4.x-example unable to retrieve config.

### ISSUE THREAD

**Issue by NikolaChen2017** [alibaba/spring-cloud-alibaba#2520]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
I pulled this repo, and the branch is 2021.x, installed the dependencies.
start up the nacos 1.4.2 (checked the doc, this is the default supported version), added test.yaml.
![image](https://user-images.githubusercontent.com/37110441/165389295-574886a4-8575-4c58-8e5d-7cde24bce601.png)

start up nacos-config-2.4.x-example main class.

then the controller response is empty object.
![image](https://user-images.githubusercontent.com/37110441/165389488-0c14d635-e559-414f-a375-0ae892dc9f8e.png)

go back to check the local resource/application.yaml, IDEA display the notifications 
'Cannot resolve configuration property 'spring.cloud.nacos.config.group''.
'Cannot resolve configuration property 'spring.cloud.nacos.config.server-addr' 

suppose the springBoot didnot read the nacos address and group?

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by steverao** [comment]
Provide your application.yaml information please, in our example, the setting document is `xxx.yml`, Please check if the suffix is correct?

**Comment by NikolaChen2017** [comment]
```
server:
  port: 8888
spring:
  application:
    name: nacos-config-import-example
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:test.yml
#      - optional:nacos:test01.yml?group=group_02
#      - optional:nacos:test02.yml?group=group_03&refreshEnabled=false
```


I commented the #2 and #3 config, or it will show error like this.

![image](https://user-images.githubusercontent.com/37110441/165447512-00ae243e-0d89-46ee-9f38-685138d5f0b7.png)
