### ISSUE TITLE
新版本的shared-configs中使用dataid的时候不需要写后缀了吗

### ISSUE THREAD

**Issue by pkaq** [alibaba/spring-cloud-alibaba#2549]
找了半天，提示文件加载了 但是environment里 size始终是0 ，最后把dataId的后缀去掉成功

**Comment by DanielLiu1123** [comment]
从 2021.0.1.0 版本开始：
- 如果使用 bootstrap.yml 方式导入外部配置，它的行为和低版本是一致的。
- 如果使用 import 方式导入外部配置
```yaml
spring:
  config:
    import:
      - optional:nacos:test.yml  # 如果有后缀会使用该后缀，没有后缀会使用默认后缀 （`spring.cloud.nacos.config.file-extension`）
``` 
dataId 和 nacos 配置中心的 dataId 保持一致，dataId 是 dataId，后缀是后缀（可以把这个后缀理解为文件类型），后缀的作用是告诉客户端解析为什么格式数据。
