### ISSUE TITLE
Flexible config for Sentinel

### ISSUE THREAD

**Issue by DanielLiu1123** [alibaba/spring-cloud-alibaba#2667]
Support Spring Cloud Gateway style config for Sentinel.

```yaml
spring:
  cloud:
    sentinel:
      flow-control:
        - predicates:
            - Path=/user/**
            - Query=name,jack
          rules:
            - grade: 1
              count: 10
        - predicates:
            - name: Query
              args:
                key: name
                value: freeman
          rules:
            - grade: 1
              count: 20
        - predicates:
            - Path=/**
          rules:
            - grade: 1
              count: 50
    degrade:
      - predicate:
          - Feign=foo
        rules:
          - grade: 2
            count: 1
            timeWindow: 10
            statIntervalMs: 1000
            minRequestAmount: 1
      - predicate:
          - name: RestTemplate
            args:
              service: foo
              path: /**
        rules:
          - grade: 2
            count: 1
            timeWindow: 10
            statIntervalMs: 1000
            minRequestAmount: 1
```
