### ISSUE TITLE
"spring.config.import" in remote config file is not work in version 2021.0.4.0

### ISSUE THREAD

**Issue by yimik** [alibaba/spring-cloud-alibaba#2833]
**Which Component**
Nacos Config

**Describe the bug**
"spring.config.import" in remote config file is not work
version 2021.0.4.0，but it work well in 2021.0.1.0

在远程配置文件中嵌套使用spring.config.import，在新版本中不管用
分析了下源码，应该是因为这一句代码
https://github.com/alibaba/spring-cloud-alibaba/blob/8c0f1a26fb7907a06f4508965974dbeff1aedaac/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/configdata/NacosConfigDataLoader.java#L106

**Comment by steverao** [comment]
“远程配置文件中嵌套使用spring.config.import，在新版本中不管用“，这里所说的不管用具体指的是什么问题？2021.0.4.0对这块是做了一些能力增强的，具体可参考相关讨论#2455

**Comment by yimik** [comment]
> “远程配置文件中嵌套使用spring.config.import，在新版本中不管用“，这里所说的不管用具体指的是什么问题？2021.0.4.0对这块是做了一些能力增强的，具体可参考相关讨论#2455

这个优化我看到了，但是我想表达的是这个优化的commit导致了一个以前可用的特性不可用了，举例如下：

本地配置文件
```yaml
# application.yml

server:
  port: 8000

spring:
  application:
    name: test
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        group: GROUP
  config:
    import:
      - optional:nacos:test.yml
```

远程配置文件
```yaml
# test.yml
spring:
  config:
    import:
      - optional:nacos:common.yml  #此配置文件引入失败，在2021.0.1.0是可以的
```

**Comment by steverao** [comment]
你直接Nacos上修改test.yml配置文件内容不能满足你的需求吗？

**Comment by steverao** [comment]
> > “远程配置文件中嵌套使用spring.config.import，在新版本中不管用“，这里所说的不管用具体指的是什么问题？2021.0.4.0对这块是做了一些能力增强的，具体可参考相关讨论#2455
> 
> 这个优化我看到了，但是我想表达的是这个优化的commit导致了一个以前可用的特性不可用了，举例如下：
> 
> 本地配置文件
> 
> ```yaml
> # application.yml
> 
> server:
>   port: 8000
> 
> spring:
>   application:
>     name: test
>   cloud:
>     nacos:
>       config:
>         server-addr: nacos-server:8848
>         group: GROUP
>   config:
>     import:
>       - optional:nacos:test.yml
> ```
> 
> 远程配置文件
> 
> ```yaml
> # test.yml
> spring:
>   config:
>     import:
>       - optional:nacos:common.yml  #此配置文件引入失败，在2021.0.1.0是可以的
> ```

你直接Nacos上修改test.yml配置文件内容不能满足你的需求吗？

**Comment by yimik** [comment]
> > > “远程配置文件中嵌套使用spring.config.import，在新版本中不管用“，这里所说的不管用具体指的是什么问题？2021.0.4.0对这块是做了一些能力增强的，具体可参考相关讨论#2455
> > 
> > 
> > 这个优化我看到了，但是我想表达的是这个优化的commit导致了一个以前可用的特性不可用了，举例如下：
> > 本地配置文件
> > ```yaml
> > # application.yml
> > 
> > server:
> >   port: 8000
> > 
> > spring:
> >   application:
> >     name: test
> >   cloud:
> >     nacos:
> >       config:
> >         server-addr: nacos-server:8848
> >         group: GROUP
> >   config:
> >     import:
> >       - optional:nacos:test.yml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 远程配置文件
> > ```yaml
> > # test.yml
> > spring:
> >   config:
> >     import:
> >       - optional:nacos:common.yml  #此配置文件引入失败，在2021.0.1.0是可以的
> > ```
> 
> 你直接Nacos上修改test.yml配置文件内容不能满足你的需求吗？

可以满足，只是之前的项目把一些公共配置提到common.yml里了，更新了之后导致之前的写法失效。

相当于在新版本中，common.yml必须在本地的配置文件中引入，如果后续不打算再支持这个功能，希望在升级指南上提示不兼容更新

**Comment by steverao** [comment]
> > > > “远程配置文件中嵌套使用spring.config.import，在新版本中不管用“，这里所说的不管用具体指的是什么问题？2021.0.4.0对这块是做了一些能力增强的，具体可参考相关讨论#2455
> > > 
> > > 
> > > 这个优化我看到了，但是我想表达的是这个优化的commit导致了一个以前可用的特性不可用了，举例如下：
> > > 本地配置文件
> > > ```yaml
> > > # application.yml
> > > 
> > > server:
> > >   port: 8000
> > > 
> > > spring:
> > >   application:
> > >     name: test
> > >   cloud:
> > >     nacos:
> > >       config:
> > >         server-addr: nacos-server:8848
> > >         group: GROUP
> > >   config:
> > >     import:
> > >       - optional:nacos:test.yml
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 远程配置文件
> > > ```yaml
> > > # test.yml
> > > spring:
> > >   config:
> > >     import:
> > >       - optional:nacos:common.yml  #此配置文件引入失败，在2021.0.1.0是可以的
> > > ```
> > 
> > 
> > 你直接Nacos上修改test.yml配置文件内容不能满足你的需求吗？
> 
> 可以满足，只是之前的项目把一些公共配置提到common.yml里了，更新了之后导致之前的写法失效。
> 
> 相当于在新版本中，common.yml必须在本地的配置文件中引入，如果后续不打算再支持这个功能，希望在升级指南上提示不兼容更新

之前也不清楚有人会这样用，所以这种情况兼容性没验证过。但是针对你抽取公共配置的需求，正常是在所有有关应用配置文件里面定义如下配置:
```
spring:
  config:
    import:
      - optional:nacos:common.yml
```
应用启动后都获取配置中心中该文件配置是不是更自然一些？
