### ISSUE TITLE
2.1.0拉取不到nacos配置

### ISSUE THREAD

**Issue by kdyzm** [alibaba/spring-cloud-alibaba#2852]
出现的问题：拉取nacos配置提示
Ignore the empty nacos configuration and get it based on dataId[xxx] & group[DEFAULT_GROUP]

实际上已经创建了配置
![image](https://user-images.githubusercontent.com/12097910/197127753-1d28ca78-5f87-4855-bd06-57b9ca2d1e1f.png)

使用的是wiki推荐的版本号
![image](https://user-images.githubusercontent.com/12097910/197127886-31338e47-908c-4f09-a19b-82d18a51d5f9.png)

配置文件如下：

``` yaml

developer:
  nacos-server-addr: 10.182.71.234:8848
  namespace: public
  group: DEFAULT_GROUP

project:
  name: ${spring.application.name}
spring:
  application:
    name: xxx
  cloud:
    nacos:
      discovery:
        server-addr: ${developer.nacos-server-addr}
        namespace: ${developer.namespace}
        group: ${developer.group}
        enabled: true
        register-enabled: true
      config:
        namespace: ${developer.namespace}
        file-extension: yml
        server-addr: ${developer.nacos-server-addr}
        group: ${developer.group}
```

我将spring boot版本号降低到2.3.4.RELEASE，将spring-cloud-alibaba-dependencies版本号降低到2.1.1.RELEASE，nacos-client强制降低到1.4.1版本号之后可以正常从2.1.0 nacos服务端拉取配置，请问下是你们的bug吗还是怎样

**Comment by steverao** [comment]
我这边使用我们example内容测试，都是正常的，可以正常获取到配置，相关测试截图：
![image](https://user-images.githubusercontent.com/25423978/197140027-5c1939be-0561-464d-a7ab-80905bc59a29.png)
建议你可以切换到相关版本，然后参考我们example内容测试一下，然后对比自己的代码。

**Comment by kdyzm** [comment]
> 我这边使用我们example内容测试，都是正常的，可以正常获取到配置，相关测试截图： ![image](https://user-images.githubusercontent.com/25423978/197140027-5c1939be-0561-464d-a7ab-80905bc59a29.png) 建议你可以切换到相关版本，然后参考我们example内容测试一下，然后对比自己的代码。

我拉取了代码并且换到了2.2.x-examples分支，改了properties配置直接运行你们的代码发现并没有异常，我将其改成yaml文件，完整的配置文件如下
``` yaml
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 10.182.71.234:8848
        refresh-enabled: true
        file-extension: yaml
  application:
    name: xxx


logging:
  level:
    com:
      alibaba:
        cloud:
          nacos:
            client: debug
```

就报错了，改成yaml文件之后在加上
``` yaml
logging:
  level:
    com:
      alibaba:
        cloud:
          nacos:
            client: debug
```
配置的情况下可以看到启动日志中打印了拉取下来的配置；但是这个配置并没有添加到spring上下文中，我写了一个controller
``` java
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @author kdyzm
 * @date 2022/10/21
 */
@RestController
public class BigController {

    @Value("${REDIS_HOST}")
    private String testStr;

    @GetMapping("/test")
    public String test(){

        return testStr;
    }
}
```
读取配置会直接报错
``` txt
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'REDIS_HOST' in value "${REDIS_HOST}"
```

总结下来：
1. 如果使用properties配置文件，不需要加上配置`logging.level.com.alibaba.cloud.nacos.client=debug`就能在启动的时候打印出拉取下来的配置文件内容；如果改成yaml文件，必须手动加上该项配置才能打印
2. 改成yaml文件中之后能拉取下来配置文件，但是无法注入到spring上下文导致使用的时候报错

运行的是
2.2.x-examples分支下的
spring-cloud-alibaba\spring-cloud-alibaba-examples\nacos-example\nacos-config-example 这个项目

**Comment by steverao** [comment]
> > 我这边使用我们example内容测试，都是正常的，可以正常获取到配置，相关测试截图： ![image](https://user-images.githubusercontent.com/25423978/197140027-5c1939be-0561-464d-a7ab-80905bc59a29.png) 建议你可以切换到相关版本，然后参考我们example内容测试一下，然后对比自己的代码。
> 
> 我拉取了代码并且换到了2.2.x-examples分支，改了properties配置直接运行你们的代码发现并没有异常，我将其改成yaml文件，完整的配置文件如下
> 
> ```yaml
> spring:
>   cloud:
>     nacos:
>       username: nacos
>       password: nacos
>       config:
>         server-addr: 10.182.71.234:8848
>         refresh-enabled: true
>         file-extension: yaml
>   application:
>     name: xxx
> 
> 
> logging:
>   level:
>     com:
>       alibaba:
>         cloud:
>           nacos:
>             client: debug
> ```
> 
> 就报错了，改成yaml文件之后在加上
> 
> ```yaml
> logging:
>   level:
>     com:
>       alibaba:
>         cloud:
>           nacos:
>             client: debug
> ```
> 
> 配置的情况下可以看到启动日志中打印了拉取下来的配置；但是这个配置并没有添加到spring上下文中，我写了一个controller
> 
> ```java
> import org.springframework.web.bind.annotation.GetMapping;
> import org.springframework.web.bind.annotation.RestController;
> 
> /**
>  * @author kdyzm
>  * @date 2022/10/21
>  */
> @RestController
> public class BigController {
> 
>     @Value("${REDIS_HOST}")
>     private String testStr;
> 
>     @GetMapping("/test")
>     public String test(){
> 
>         return testStr;
>     }
> }
> ```
> 
> 读取配置会直接报错
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'REDIS_HOST' in value "${REDIS_HOST}"
> ```
> 
> 总结下来：
> 
> 1. 如果使用properties配置文件，不需要加上配置`logging.level.com.alibaba.cloud.nacos.client=debug`就能在启动的时候打印出拉取下来的配置文件内容；如果改成yaml文件，必须手动加上该项配置才能打印
> 2. 改成yaml文件中之后能拉取下来配置文件，但是无法注入到spring上下文导致使用的时候报错
> 
> 运行的是 2.2.x-examples分支下的 spring-cloud-alibaba\spring-cloud-alibaba-examples\nacos-example\nacos-config-example 这个项目

第1：直接使用2.2.x分支，不要使用你刚才说的分支，那是我们特殊的非主干分支。然后，我使用相关demo测试，没有发现你说的第一个问题，如果不加打印配置参数，不会有配置打印，加了才会打印。第2：我没有复现出你说的第二点，能拉下来配置但是无法注入到spring上下文，你确定配置确实被拉下来了吗？下图是我的验证结果：
![image](https://user-images.githubusercontent.com/25423978/197234796-63bb5752-7d34-4209-a446-547b79d9b523.png)

**Comment by kdyzm** [comment]
我找到问题了。。不是上面的问题，是我重现的时候搞混了


真正的问题是下面的这行配置
``` yaml
spring:
  cloud:
    nacos:
      config:
        namespace: public
```

在2.1.0下如果命名空间是public的话，这个配置不能写成public，解决方案就是不写这个配置；但是在1.4.1下是允许写成public的，在直接升级1.4.1到2.1.0的时候就暴露出来了这个问题，之前可能是我频繁修改配置但是idea有问题导致缓存了上个版本的修改，现在未重现之前说的问题。

非常感谢帮忙排查问题，这个public的问题能不能做个优化呀，否则直接升级1.4.1到2.1.0很容易踩坑的
