### ISSUE TITLE
单机开启多消费者实例无法保证分区有序吗

### ISSUE THREAD

**Issue by 15231171965** [alibaba/spring-cloud-alibaba#2941]
问题：
目前我的服务配置了如下属性
spring.cloud.stream.bindings.<channelName>.consumer.concurrency=3
单机开启了3个线程作为独立的消费者实例。
按照消费的模型来讲，每个RocketMQ Topic的一个分区，只会被一个消费者实例所消费。
但是我观察到的现象，一个Topic的同一个分区的消息被此机器的多个消费者实例所消费。
concurrency开多个的话，无法保证一个分区只被一个消费者实例所消费这个特性嘛

Question:
Currently my service is configured with the following properties
spring.cloud.stream.bindings..consumer.concurrency=3
The single machine starts three threads as separate consumer instances.

According to the consumption model, one partition per RocketMQ Topic will only be consumed by one consumer instance.
But what I have observed is that messages from the same partition of a Topic are consumed by multiple consumer instances of that machine.

With multiple concurrency concurrency, there is no guarantee that only one consumer instance of a partition should be running this feature

参考资料：
https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR3/reference/htmlsingle/#_producers_and_consumers

Reference Materials：
https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR3/reference/htmlsingle/#_producers_and_consumers

**Comment by 123liuziming** [comment]
可能需要看一下这三个消费者是不是在一个消费者组里的？

**Comment by 123liuziming** [comment]
默认创建出来一个Topic应该有四个消费队列，设置只有三个消费者的话确实有可能一个消费者消费多个队列吧

**Comment by 15231171965** [comment]
@123liuziming 
我理解应该是这种模型：
Customer------1:N------Queue
Queue---------1:1-------Customer

现在问题是一个Queue的消息，会被同一台机器上的三个消费者消费，这样无法保证Queue的消息消费顺序性。
我的疑问是这个。

I understand it to be this model:
Customer------1:N------Queue
Queue---------1:1-------Customer

The problem is that a Queue message will be consumed by three consumers on the same machine, so there is no guarantee that the Queue message consumption order is guaranteed.
My question is this.

**Comment by 15231171965** [comment]
@123liuziming 感谢解答
I look forward to and thank you for your answers

**Comment by 123liuziming** [comment]
@15231171965 
开启了三个线程，但是消费者实例应该还是只有一个，我理解不是一个线程就对应一个消费者实例的，
![image](https://user-images.githubusercontent.com/32130965/206369833-ac9344f3-5adf-4a3b-bf7a-3b6a287bccf1.png)
![image](https://user-images.githubusercontent.com/32130965/206369867-d67ee39b-d0c5-4523-a702-74f793428442.png)
我配置了如上图所示的一对消费者和生产者，concurrency设置为3
![image](https://user-images.githubusercontent.com/32130965/206370071-a70cae02-b181-429b-8a1b-db055f436b4b.png)
![image](https://user-images.githubusercontent.com/32130965/206370127-239e24bc-cd8e-440e-bcce-d95779313f26.png)
可以看到，使用了不同的线程消费，但是消费者的标识都是同一个
比如我开启两个消费者，RocketMQ就会负载均衡为每个消费者消费两个队列，但是一个队列只会被一个消费者消费
![image](https://user-images.githubusercontent.com/32130965/206371065-21048bb4-8117-4177-9f7c-5f0a145d5cd1.png)

**Comment by 15231171965** [comment]
@123liuziming 
我理解按你描述的模型，是无法保证concurrency = n(n > 1)的场景时，保证消息的分区有序性。因为单分区的消息被多线程消费了。
如果我想保证单分区的消息有序消费，那么需要开启spring cloud stream的 partitioned能力吗？ 设置partitioned = true。

此时 spring cloud stream是否会通过自己的分区能力来保证分区有序性

I understand that as you describe the model, it is not possible to guarantee concurrency = n(n > 1) and partition order of messages. Because single-partition messages are consumed by multiple threads.
Do I need to enable partitioned on spring cloud stream if I want to keep my single-partitioned messages consumed in order? Set partitioned = true.

Whether spring cloud stream will use its own partitioning ability to ensure partition order

**Comment by 123liuziming** [comment]
> @123liuziming 我理解按你描述的模型，是无法保证concurrency = n(n > 1)的场景时，保证消息的分区有序性。因为单分区的消息被多线程消费了。 如果我想保证单分区的消息有序消费，那么需要开启spring cloud stream的 partitioned能力吗？ 设置partitioned = true。
> 
> 此时 spring cloud stream是否会通过自己的分区能力来保证分区有序性
> 
> I understand that as you describe the model, it is not possible to guarantee concurrency = n(n > 1) and partition order of messages. Because single-partition messages are consumed by multiple threads. Do I need to enable partitioned on spring cloud stream if I want to keep my single-partitioned messages consumed in order? Set partitioned = true.
> 
> Whether spring cloud stream will use its own partitioning ability to ensure partition order

是的，我做了如下配置
生产者端：
```
server:
  port: 28085
spring:
  application:
    name: rocketmq-broadcast-producer-example
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          producer-out-0:
            producer:
              group: output_1
      bindings:
        producer-out-0:
          destination: broadcast
          producer:
            partition-key-expression: payload # 配置分区键的表达式规则
            partition-count: 2 # 配置消息分区的数量
logging:
  level:
    org.springframework.context.support: debug
```
这样配置限制了生产者会按照消息体的内容发送消息到两个分区
之后我用生产者连续发送相同的消息，并且用两个消费者同时消费这个生产者生产的消息
```
server:
  port: 28084
spring:
  application:
    name: rocketmq-broadcast-consumer2-example
  cloud:
    stream:
      function:
        definition: consumer;
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        consumer-in-0:
          destination: broadcast
          group: broadcast-consumer
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 1

logging:
  level:
    org.springframework.context.support: debug

```
```
server:
  port: 28084
spring:
  application:
    name: rocketmq-broadcast-consumer1-example
  cloud:
    stream:
      function:
        definition: consumer;
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        consumer-in-0:
          destination: broadcast
          group: broadcast-consumer
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 0

logging:
  level:
    org.springframework.context.support: debug
```
实验结果是只有一个消费者收到了生产者发送的消息，这是符合预期的，说明这个消费者只消费了指定的那个分区。
![image](https://user-images.githubusercontent.com/32130965/207312398-0438157f-1006-4042-8b63-90902f597929.png)
![image](https://user-images.githubusercontent.com/32130965/207312445-ef7f6ecb-aec4-4ce3-bdce-bfb78a1853b4.png)
