### ISSUE TITLE
file extension for shared-config and extension-config

### ISSUE THREAD

**Issue by zerocoolys** [alibaba/spring-cloud-alibaba#3138]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
spring-cloud-starter-alibaba-nacos-config @ 2021.X

**Is your feature request related to a problem? Please describe.**
The `shared-configs` or `extension-configs` do not have a file extension property. The Java type for config mapping is `com.alibaba.cloud.nacos.NacosConfigProperties.Config`. In such a scenario, we must include the file extension in the dataId if the config extension is not **properties** (which is the default). For instance, the dataId would be 'shared-config.yaml'. This naming convention differs from the standard dataId configuration.

**Describe the solution you'd like**
a new `fileExtension` field in `com.alibaba.cloud.nacos.NacosConfigProperties.Config`. Callers can retrieve the ext value of the config from this field first, and then from the dataId if `ext` is blank. we can provide a common method to encapsulate this part.

**Describe alternatives you've considered**

**Additional context**

**Comment by ruansheng8** [comment]
Would you like to omit the `file-extension` in `data-id` by configuring a default file extension? 
For example, if `file-extension=yml` is configured and `data-id=test-config`, the `test-config` configuration would automatically be parsed using `YmlProcessor`.

**Comment by zerocoolys** [comment]
> 

Hi, it doesn't work for `extension-config` or `shared-config`.

for example 
```yaml
      config:
        server-addr: 127.0.0.1:8848
        data-id: config-name # `config-name` with `yaml` type can be retrieve correctly
        file-extension: yaml
        shared-configs:
          - dataId: common-1 # not working if you have a configuration with name `common-1` and type `yaml` 
            refresh: true
          - dataId: common-2.yaml # working, since nacos will parse dataId and get the file extension, but you have to set config name to `common-2.yaml`
            refresh: true

```

below is the code 

https://github.com/alibaba/spring-cloud-alibaba/blob/5ab4f22e8e27c1e9268f1beeb4fb117ea42ea1e5/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java#L155
