### ISSUE TITLE
请问如何让所有接口都默认开启监控，而不需要每个controller下的方法加@SentinelResource

### ISSUE THREAD

**Issue by heqs** [alibaba/spring-cloud-alibaba#3224]
旧的项目接口非常多，希望默认就对所有接口都监控，但是目前是必须加@SentinelResource的方法才能在sentinel控制台看到，以下是我的配置
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.121:8848 #Nacos地址
        weight: 1
        enabled: true
        register-enabled: false
      config:
        server-addr: http://192.168.1.121:8848 #Nacos地址
        file-extension: yaml
        enabled: false
        refresh-enabled: false
    sentinel:
      transport:
        dashboard: 192.168.1.121:8858
        port: 8719
        heartbeat-interval-ms: 5000
        namespace: mall
      filter:
        enabled: true
        url-patterns: /**
      eager:
        enabled: true
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.121:8848
            dataId: mall-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
```
