### ISSUE TITLE
Discussion: Disable the Endpoint node information in the spring cloud alibaba example module by default

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3284]
The EndPoint node information exposes some sensitive information to the public network, causing security risks.

eg: If database information is configured in nacos config module, database password, user name, ip address and other information is likely to be exposed!

**Comment by steverao** [comment]
Now, its default switch of relevant interface is close. For users, if they want to call relevant interface, such as `http://127.0.0.1:18083/actuator/nacosdiscovery`, they need to add following configuration:
```shell
management.endpoints.web.exposure.include=*
```

**Comment by ruansheng8** [comment]
见 `http://localhost:28888/actuator/env`
如果用户使用 `*` 暴露actuator端口, 会导致nacos config所有配置泄漏, 存在安全隐患.

```yaml
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yml
        shared-configs:
          - dataId: database.yml
            group: TEST
management:
  endpoints:
    web:
      exposure:
        include: "*"
```

![image](https://user-images.githubusercontent.com/24709538/234869208-7c5dd2b9-0493-449a-a828-2b18c6c3b9fb.png)

![image](https://user-images.githubusercontent.com/24709538/234869137-24726dcd-7bb8-43b8-9a40-a091fcb4d96f.png)
