### ISSUE TITLE
how to config " listOfServers "  Spring Cloud 2021.x  ? 

### ISSUE THREAD

**Issue by chen-jie** [alibaba/spring-cloud-alibaba#3353]
**Which Component**
 Nacos Discovery

**Is your feature request related to a problem? Please describe.**
since spring Cloud 2021.x already removed ribbon, configuration like this is not working 

```
my-micoservice:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8888
```

Is there any other way ?

**Comment by chen-jie** [comment]
I find a way to do this. Using [SimpleDiscoveryClient](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#simplediscoveryclient) . 
Be careful to set `order:  -1` otherwise spring cloud will use NacosDiscoveryClient to resolve 'my-micoservice' first
```
spring:
  cloud:
    discovery:
      client:
        simple:
          order: -1
          instances:
            my-micoservice:
              -   uri: http://localhost:8888
    nacos:
      discovery:
        server-addr: http://nacos.foo.bar
        namespace:xxx
        username: xxxx
        password: xxxx
```
