### ISSUE TITLE
springboot 项目启动时无法正常获取nacos config 远程配置文件

### ISSUE THREAD

**Issue by mazimin** [alibaba/spring-cloud-alibaba#3374]
nacos config

遇到问题：
springboot 项目启动时无法正常获取nacos config 远程配置文件

debug 跟踪代码排查
1. NacosConfigDataLoader.doLoad 一路跟踪到LocalConfigInfoProcessor.getFailoverFile 发现程序在本地读取了不存在文件，然后继续跟踪到RpcClient.request 方法 抛出异常 throw new NacosException(-401, "Client not connected, current status:" + this.rpcClientStatus.get());
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/7046e4ff-3f7d-489e-8a0c-602d3a37a19a)

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/6277eeb1-c086-4eeb-afdf-a4341158370e)

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/32f1dc35-a76c-4ca7-afa6-2c0c7afddc37)

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/306b11f0-715c-4f08-8fba-16bf7da662be)
2. 我尝试在启动springboot项目时http 调用 nacos config 接口可以正常访问返回数据
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/57e19926-a474-4c61-931f-cfa68bbf8276)

3. 然后我将 nacos_client 版本回退到1.4.1可以正常获取配置文件

4.版本
spring-boot.version：2.7.11
spring-cloud.version：2021.0.5
spring-cloud-alibaba.version：2021.0.5.0
nacos.client.version1.4.1：2.2.1

不回退nacos_client版本如何可以正确获取到配置

**Comment by mazimin** [comment]
nacos 版本 2.2.0

**Comment by yuluo-yx** [comment]
方便提供一个可以复现问题的最小example吗？方便社区同学复现并解决问题！

**Comment by mazimin** [comment]
https://github.com/mazimin/demo1  demo地址您看一下

**Comment by yuluo-yx** [comment]
> https://github.com/mazimin/demo1 demo地址您看一下

namespace 配置有问题，可以直接指定命名空间的序列号或者是不指定，使用默认值

**Comment by yuluo-yx** [comment]
> https://github.com/mazimin/demo1 demo地址您看一下

如下是我的测试结果：
```
2023-07-04 19:36:19.032  INFO 9952 --- [           main] c.a.c.n.refresh.NacosContextRefresher    : [Nacos Config] Listening config: dataId=demo1.yml, group=DEFAULT_GROUP
value：test
```

配置如下：
```
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: DEFAULT_GROUP
#        namespace: ${spring.profiles.active}
      config:
        group: DEFAULT_GROUP
#        namespace: ${spring.profiles.active}
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
```
启动类
```
    public static void main(String[] args) throws NacosException {
        SpringApplication.run(Demo1Application.class, args);
        NacosConfigManager bean = SpringUtils.getBean(NacosConfigManager.class);
        String default_group = bean.getConfigService().getConfig("demo1.yml", "DEFAULT_GROUP", 3000);
        System.out.println("value：" + default_group);
    }
```

**Comment by mazimin** [comment]
配置
```yml
# Spring
spring:
  application:
    # 应用名称
    name: demo1
  profiles:
    # 环境配置
    active: ${RUN_ENV:dev}

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 8848.gr55a24e.y8ki2rcl.a19d84.grapps.cn:80
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        # 配置文件格式
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
```
启动类
```java
@SpringBootApplication
public class Demo1Application {

    public static void main(String[] args) throws NacosException {
        SpringApplication.run(Demo1Application.class, args);
        NacosConfigManager bean = SpringUtils.getBean(NacosConfigManager.class);
        String default_group = bean.getConfigService().getConfig("demo1.yml", "DEFAULT_GROUP", 3000);
        System.out.println(default_group);
    }
}
```
这是我的namespace 
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/51228023/c0977c29-0b94-40c8-8cff-db12cadbd2af)
运行结果
```
2023-07-04 20:19:00.802  INFO 32120 --- [           main] com.example.demo.Demo1Application        : The following 1 profile is active: "dev"
2023-07-04 20:19:00.823  WARN 32120 --- [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] config[dataId=demo1.yml, group=DEFAULT_GROUP] is empty
2023-07-04 20:19:00.823 DEBUG 32120 --- [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] config[dataId=demo1.yml, group=DEFAULT_GROUP] content: 
null
```
只要一降client 版本就正常  升级回来 就无法获取
