### ISSUE TITLE
there is an error in example code

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3523]
location: https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/integrated-example/config-init/config/integrated-consumer.yaml

```
    stream:
      bindings:
        praise-input:
          destination: PRAISE-TOPIC-01
          content-type: application/json
          group: praise-consumer-group-PRAISE-TOPIC-01
      rocketmq:
        binder:
          name-server: rocketmq:9876
        bindings:
          praise-input:
            consumer:
              pullInterval: 4000
              pullBatchSize: 4
```

should chang to 
```
    stream:
      function:
        definition: consumer;
      bindings:
        consumer-in-0:
          destination: PRAISE-TOPIC-01
          content-type: application/json
          group: praise-consumer-group-PRAISE-TOPIC-01
      rocketmq:
        binder:
          name-server: rocketmq:9876
        bindings:
          consumer-in-0:
            consumer:
              pullInterval: 4000
              pullBatchSize: 4
```

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/27885492/2bae809c-10ba-4e54-aa9f-db7ad8af05e3)
