### ISSUE TITLE
2021.0.5 spring-cloud-starter-alibaba-nacos-config 如何设置本地配置优先级最高？

### ISSUE THREAD

**Issue by walkwolf** [alibaba/spring-cloud-alibaba#3636]
**Which Component**
Nacos 2.2.3
spring-cloud-alibaba 2021.0.5.0
springboot 2.6.13

**Describe what problem you have encountered**

述求：nacos 配置中心有应用的数据库连接配置，应用启动时，想使用本地配置的 DB用户、密码覆盖nacos配置
项目结构：项目通过bootstrap引入nacos config，配置项为 namespace + server-addr 。

- 尝试1：应用启动加参数、在bootstrap.yml application.yml文件中配置用户密码， 均未成功，引用的还是nacos配置中心的配置。
- 尝试2：通过spring.config.import 方式最后加载本地文件，未成功
- 尝试3：翻看issues 关联 涉及到 `spring.cloud.nacos.config.preference` 最新2021.x源码中未发现应用（REMOTE将使用`org.springframework.boot.context.config.ConfigData.Option.PROFILE_SPECIFIC`），但和这个选项本已有歧义吧，在`spring-configuration-metadata.json` 中有定义，尽管  `#2455` 中详细说明了配置，仍然未成功
  - #2455 
  - #2459 
  - #2808 

是否有可能这样操作？

**Comment by ruansheng8** [comment]
配置优先级规则遵循 Spring Cloud 的规范（上面加载的配置项会覆盖下面加载的配置项）：
- 启动命令中指定的配置项；
- 操作系统配置项 (System.getProperties())
- 操作系统环境变量
- 配置中心中的配置文件；
- 本地的application.properties(yml)
- 本地boostrap.properties（yml）

如果希望本地配置不被远程的覆盖，应该将本地对应的 `spring.config.import` 配置移除掉，或者通过 `profile` 来动态控制，而不是去违反相关规范，因为这样加大后续问题定位的难度。

**Comment by ruansheng8** [comment]
要实现你的需求，方式其实有很多种，例如：远程配置上维护通用配置，然后应用 `application.yml` 配置文件使用属性引用的方式

例如在 Nacos 维护的配置都是以 global.xxx 开头，业务服务那边按需引用，如果本地配置不希望被覆盖，则直接写死即可，这样就不存在配置覆盖的问题
```yaml
spring:
  datasource:
    # database.properties 中有 global.xxx 相关配置
    username: ${global.database.testdb1.username}
    password: ${global.database.testdb1.password}
    url: ${global.database.testdb1.url}
    driver-class-name: ${global.database.testdb1.driverClassName}
    # 不引用远程配置，直接写死的情况
    type: com.alibaba.druid.pool.DruidDataSource
  config:
    import:
      - nacos:database.properties?refresh=true
```

**Comment by walkwolf** [comment]
> 配置优先级规则遵循 Spring Cloud 的规范（上面加载的配置项会覆盖下面加载的配置项）：
> 
> * 启动命令中指定的配置项；
> * 操作系统配置项 (System.getProperties())
> * 操作系统环境变量
> * 配置中心中的配置文件；
> * 本地的application.properties(yml)
> * 本地boostrap.properties（yml）
> 
> 如果希望本地配置不被远程的覆盖，应该将本地对应的 `spring.config.import` 配置移除掉，或者通过 `profile` 来动态控制，而不是去违反相关规范，因为这样加大后续问题定位的难度。

感谢，我刚写了个最简项目，配置优先级没问题，正在排查项目未覆盖原因

**Comment by walkwolf** [comment]
> 配置优先级规则遵循 Spring Cloud 的规范（上面加载的配置项会覆盖下面加载的配置项）：
> 
> * 启动命令中指定的配置项；
> * 操作系统配置项 (System.getProperties())
> * 操作系统环境变量
> * 配置中心中的配置文件；
> * 本地的application.properties(yml)
> * 本地boostrap.properties（yml）
> 
> 如果希望本地配置不被远程的覆盖，应该将本地对应的 `spring.config.import` 配置移除掉，或者通过 `profile` 来动态控制，而不是去违反相关规范，因为这样加大后续问题定位的难度。

做了最简项目的测试，还是不行（中间成功一次是因为没找到nacos配置，dev.name = vm）

为什么会覆盖本地呢？代码  https://github.com/walkwolf/nacos-config-cloud.git

- 程序运行参数 -Ddev.name=vmparam
- bootstrap.yml 配置 dev.name=bootstrap.yml
- application.yml 配置 dev.name=application.yml
- nacos 测试配置
  - nacos 配置dataid:test  格式Properties
  - nacos 配置dataid:test.properties  格式Properties
  - nacos 配置dataid:test  格式yaml,开启 bootstrap 中 file-extension: yaml
  - nacos 配置dataid:test.yaml  格式yaml,开启 bootstrap 中 file-extension: yaml

## 结论？？？
1. 只要nacos配置命中，则nacos中dev.name生效，并且最高优先级？？
2. nacos不命中，则vm参数优先。
期望：nacos命中，可以vm 或者本地配置优先

**Comment by walkwolf** [comment]
> 要实现你的需求，方式其实有很多种，例如：远程配置上维护通用配置，然后应用 `application.yml` 配置文件使用属性引用的方式
> 
> 例如在 Nacos 维护的配置都是以 global.xxx 开头，业务服务那边按需引用，如果本地配置不希望被覆盖，则直接写死即可，这样就不存在配置覆盖的问题
> ...

这是一个好方法，就是bean/list 配置没有yml那么直接

**Comment by ruansheng8** [comment]
@walkwolf  把你测试项目里面的 bootstrap 依赖移除掉，然后使用上面的 `spring.config.import` 试试看，Spring Boot 2.4 以后的版本 Spring 官方已经不推荐使用 bootstrap 的方式了。
另外，如果 Nacos 的配置是 yaml 格式的会，最好给配置ID加上 .yml 或者 .yaml 后缀。
我这边本地用你的测试项目验证 `spring.config.import` 方式没有问题

**Comment by walkwolf** [comment]
> * 配置中心中的配置文件；

感谢 @ruansheng8 

去除bootstrap 使用 import 方式解决了顺序，vm参数第一。刚刚卡在namespace 位置好久
完全弃用 bootstrap(.yml .properties pom) 后，namespace 可以写在application中才可以找到对应的配置
**现有的官网配置要求可能就不对了 2021.0.4 2021.0.5**

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/12028532/cd038efa-5e7f-4b30-b46b-ef5b172fecf1)

这样就可以 通过vm递送特殊参数，其他变量完全依赖于nacos了。但使用了import 就不能使用properties。如果想完全使用本地环境，就需要在application.yml 中定义  dev profile, `spring.config.import classpath:foo.yml` 了

**Comment by walkwolf** [comment]
```
spring:
  config:
    import:
      - nacos:test.yml
      - classpath:local.yml
```
这样就可以加载本地配置了，但有的项目不好用，需要进一步校验

校验完成 2021.0.4/5
1. 当application.yml 中使用 profile 时，vm 可用（优先级最高），classpath 可用 ，优先级大于nacos
2. 当application.yml 中未使用 profile 时，vm 可用（优先级最高），config import classpath 优先级小于nacos
