### ISSUE TITLE
共享配置和扩展配置是否也能加一个fileExtension这样的参数 

### ISSUE THREAD

**Issue by publicize-y** [alibaba/spring-cloud-alibaba#3657]
目前在用nacos的共享配置和扩展配置时，控制台的Data Id必须带类型尾缀，实际使用过程中感觉不太方便。目前我们想把共享配置的文件类型给更改掉，文件由properties改成yaml，我们发现不支持修改DataId，导致只能把共享配置给重新删掉，新建一个配置 取名以yaml结尾。这里的共享配置和扩展配置是否能增加一个fileExtension这样的参数，便于修改

**Comment by publicize-y** [comment]
![1](https://github.com/alibaba/spring-cloud-alibaba/assets/73219873/8e56795b-9a70-40d4-b851-90fa7ddc9579)
![2](https://github.com/alibaba/spring-cloud-alibaba/assets/73219873/32bdeda8-7632-4085-9d88-64dbbdb44131)

**Comment by yuluo-yx** [comment]
cc @ruansheng8

**Comment by publicize-y** [comment]
如果确定更改的话，我可以尝试一下

**Comment by ruansheng8** [comment]
@publicize-y  可以试试下面的配置方式是否可以满足你的需要
```
spring:
  cloud:
    nacos:
      config:
        file-extension: yml
        shared-configs:
          - dataId: customConfig.${spring.cloud.nacos.config.file-extension}
```
