### ISSUE TITLE
bug[sentinel]: when use openfeign, sentinel consoleserverlist is null

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3707]
sentinel openfeign example:

application.yml config:

```yml
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8080
      eager: true
```

In sentinel-core-example. the consoleservelist has value.

![4c0efb8b0b62bc41747ff85675dd8fae](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/87147d67-2f35-4d7e-bc01-1bba4c596745)
