### ISSUE TITLE
spring cloud gateway got an error strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by 4d4d4d4** [alibaba/spring-cloud-alibaba#3797]
spring cloud starter gateway 4.1.4
It is expected that the request can be forwarded to the interface of other microservices through the gatew
The request will encounter an error in the browser
![image](https://github.com/user-attachments/assets/5389b8a0-84b0-43c6-8fce-e8497e6a313a)
The attempt on apifox was successful
![image](https://github.com/user-attachments/assets/897e18cc-81e2-4ad0-bccd-162806faae8d)
This is the apifox request header information, according to reason should not encounter cross-domain issues I really don't understand want to ask for some advice
![image](https://github.com/user-attachments/assets/deb76418-16ee-4530-996c-499bd73aba67)

**Comment by 4d4d4d4** [comment]
Related Configuration
`server:
  port: 6000
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "**"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 36000
      routes:
        - id: member
          uri: http://127.0.0.1:6001
          predicates:
            - Path=/member/**
`

**Comment by 4d4d4d4** [comment]
Related Configuration
`server:
  port: 6000
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "**"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 36000
      routes:
        - id: member
          uri: http://127.0.0.1:6001
          predicates:
            - Path=/member/**
`

**Comment by 4d4d4d4** [comment]
```
Related Configuration
server:
  port: 6000
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "**"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 36000
      routes:
        - id: member
          uri: http://127.0.0.1:6001
          predicates:
            - Path=/member/**
```
