### ISSUE TITLE
Can't read config from spring, when without ".yml"

### ISSUE THREAD

**Issue by Sorieee** [alibaba/spring-cloud-alibaba#3810]
**Which Component**
Nacos Config
**Describe the bug**
When I config like this, code can't read config from spring.
```yml
  config:
    import:
      - nacos:${spring.application.name}?refreshEnabled=true&group=DEFAULT_GROUP
```
`NacosConfigDataLoader` can pull config from server
![image](https://github.com/user-attachments/assets/c6f9d530-4c74-452a-a63f-d1a250d6e770)
But 
![image](https://github.com/user-attachments/assets/ad8fa8c2-0787-4707-ad73-898799dfc22a)
When I config
```yml
config:
    import:
      - nacos:${spring.application.name}.yml?refreshEnabled=true&group=DEFAULT_GROUP
```
Can read config
![image](https://github.com/user-attachments/assets/42ec6e1d-4862-4c26-87cf-ce41976eaa70)
ConfigPrinter
```java
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class ConfigPrinter implements CommandLineRunner {

    @Value("${spring.datasource.url:}")
    private String datasourceUrl;

    @Value("${spring.datasource.username:}")
    private String datasourceUsername;

    @Value("${spring.datasource.password:}")
    private String datasourcePassword;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Datasource URL: " + datasourceUrl);
        System.out.println("Datasource Username: " + datasourceUsername);
        System.out.println("Datasource Password: " + datasourcePassword);
    }
}
```
**Additional context**
JDK21
```xml
<spring-boot.version>3.2.0</spring-boot.version>
<spring-cloud-alibaba.version>2023.0.1.0</spring-cloud-alibaba.version>
<spring-cloud.version>2023.0.3</spring-cloud.version>
```
