### ISSUE TITLE
Spring Cloud Stream with RocketMQ and facing an issue where defining multiple consumers results in a problem with message consumption.

### ISSUE THREAD

**Issue by cy503328434** [alibaba/spring-cloud-alibaba#3830]
**Which Component**

Spring Boot Version: 3.3.2
Spring Cloud Version: 2023.0.3
Spring Cloud Alibaba Version: 2023.0.1.2

**Describe what problem you have encountered**

### **Configuration:**

**`application.yml` Configuration:**

```yaml
spring:
  cloud:
    stream:
      binders:
        binder1:
          type: rocketmq
          environment:
            spring.cloud.stream.rocketmq:
              binder:
                name-server: localhost1:9876
                secret-key: mall
                access-key: [ACCESS_KEY]
                enable-msg-trace: false
                group: crm-refactor-group-1
              bindings:
                topic-demo-out-0:
                  producer:
                    group: delayed-group-1
                    sync: true
                handleDemoMsg-in-0:
                  consumer:
                    enable: true
                    broadcasting: false
                    orderly: false
                handleCompletedMsg-in-0:
                  consumer:
                    enable: true
                    broadcasting: false
                    orderly: false
        binder2:
          type: rocketmq
          environment:
            spring.cloud.stream.rocketmq:
              binder:
                name-server: localhost2:9876
                enable-msg-trace: false
                group: crm-refactor-group-1
              bindings:
                topic-demo2-out-0:
                  producer:
                    group: delayed-group-2
                    sync: true
      default-binder: binder1
      bindings:
        producer1-out-0:
          destination: MQ_CLIENT_DEMO_LOCAL1_TOPIC
          binder: binder1
        producer2-out-0:
          destination: MQ_CLIENT_DEMO_LOCAL2_TOPIC
          binder: binder2
        consumer1-in-0:
          destination: MQ_CLIENT_DEMO_LOCAL1_TOPIC
          content-type: application/json
          group: MQ_CLIENT_DEMO_LOCAL1_GROUP
          binder: binder1
        consumer2-in-0:
          destination: MQ_CLIENT_DEMO_LOCAL2_TOPIC
          content-type: application/json
          group: MQ_CLIENT_DEMO_LOCAL2_GROUP
          binder: binder2
```

**Consumer Beans:**

```java
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

import java.util.function.Consumer;

@Component
public class MessageConsumers {

    @Bean
    public Consumer<Message<JSONObject>> consumer1() {
        return msg -> {
            log.info("{} Receive New Messages1: {} Headers: {}", Thread.currentThread().getName(), msg.getPayload(), msg.getHeaders());
        };
    }

    @Bean
    public Consumer<Message<JSONObject>> consumer2() {
        return msg -> {
            log.info("{} Receive New Messages2: {} Headers: {}", Thread.currentThread().getName(), msg.getPayload(), msg.getHeaders());
        };
    }
}
```

### **Issue:**

When both `consumer1` and `consumer2` are defined and running in the same application, neither consumer processes messages correctly. However, when only one of the consumers is active, it works fine.

### **Request for Assistance:**

1. **Compatibility:** Are there known compatibility issues with Spring Cloud Stream and RocketMQ versions?
2. **Configuration Guidance:** Can you provide guidance on how to configure multiple consumers correctly in this environment?
3. **Debugging Tips:** Any additional debugging tips or tools that might help resolve this issue?
4. 

**Describe what information you have read**

1. **Configuration Review:** Verified that each consumer has a unique `destination` and `group`.
2. **Bean Names:** Ensured that each consumer Bean is uniquely named.
3. **RocketMQ Console:** Checked the status of topics and consumers in the RocketMQ management console.
4. **Logs:** Analyzed application logs for errors or warnings.
