### ISSUE TITLE
After upgrading from `2023.0.1.2` to `2023.0.1.3`, my project fails to start

### ISSUE THREAD

**Issue by troyzhxu** [alibaba/spring-cloud-alibaba#3881]
## Framework versions

* SpringBoot Version: `3.3.5`
* SpringCloud Version: `2023.0.3`
* SpringCloudAlibaba : `2023.0.1.2` -> `2023.0.1.3`

## Configuration in `bootstrap.yml`

```yml
spring:
  application:
    name: xxxxxx
  cloud:
    nacos:
      config:
        file-extension: yml
      server-addr: x.x.x.x:xxxx
      username: xxxx
      password: xxxx
```

## Configuration of DataSource in Nacos：

```yml
spring:
  datasource:
    url: jdbc:mysql://xxxxx/xxxx
    username: xxxx
    password: xxxx
```

## Error Message

* After upgrading SpringCloudAlibaba from `2023.0.1.2` to `2023.0.1.3`, my project fails to start with the following errors：

```txt
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).
```

* If downgraded SpringCloudAlibaba  to `2023.0.1.2`, it immediately works ok.

**Comment by yuluo-yx** [comment]
感觉不像是 srping cloud alibaba 的问题，sca 没有和数据库相关的代码部分。

可以看看最新的 spring boot 版本和用的 orm 框架是不是兼容。或者能提供一个复现的最简例子，我们本地复现看看

**Comment by herodotus-ecosystem** [comment]
错误信息显示的是数据库问题，是因为服务启动时数据库相关内容加载的比较早。本质是因为无法读取到Nacos 的配置，读不到 Nacos 的配置所以首先抛出数据库连接问题。

这个问题与 #3877 #3874 和 #3876 是同一个问题。2023.0.1.2 运行正常，升级到 2023.0.1.3 就会出问题。

2023.0.1.3 目测最大的变化是提取出了一个配置模块。bootstrap 和 import 两种配置读取方式一直都是同时支持的，逻辑上不应该重构了代码就支持某一种了。个人猜测是 #3878 所致。

**Comment by herodotus-ecosystem** [comment]
在IDEA 中，sca 的配置是有提示的。但是升级到了 2023.0.1.3，sca config 相关配置，在 IDEA 中不仅不会提示，还会出现不存在的提示。

虽然，sca 2023.0.1.3 中还是有 NacosConfigProperties 类，但是，这些代码被放在了 文件夹 `com.alibaba.cloud.nacos` 下，而不是文件夹 `com/alibaba/cloud/nacos`下面，是非正常的 java packages。虽然也进行了自动配置，但是从 IDEA 中表现来看，明显就是没有正常注入。换句话说，Spring Boot 只扫描了 包(文件夹) `com/alibaba/cloud/nacos`，不会去扫描文件夹 `com.alibaba.cloud.nacos`

**Comment by herodotus-ecosystem** [comment]
![image](https://github.com/user-attachments/assets/04aa57f8-215a-4d7a-8e77-cfd13a819364)

上图中，`1` 对应的目录为，后面称之为目录一

![image](https://github.com/user-attachments/assets/629ae26a-756a-45b3-ad84-05f6f120fad2)

上图中，`2` 对应的目录为，后面称之为目录二

![image](https://github.com/user-attachments/assets/67021345-5931-4330-967d-e19344c04d50)

## 这里的问题可以看 Spring Boot 自动配置机制

`spring-alibaba-nacos.config` 模块下载 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 中的配置如下：

```shell
com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
com.alibaba.cloud.nacos.endpoint.NacosConfigEndpointAutoConfiguration
```

从 Spring Boot 自动配置机制来说，`com.alibaba.cloud.nacos.NacosConfigAutoConfiguration` 是告诉 Spring Boot 从前面“目录一”的目录中读取类 `NacosConfigAutoConfiguration`。但是 2023.0.1.3 `spring-alibaba-nacos-config` 模块下， 98% 的代码都被放到 “目录二” 文件加下。从该模块的字自动配置文件中看看不出问题的，都是一样的，但是实际应该是找不到类的。

## 另外的问题

原本想如果仅是改一个文件夹的问题，那么我就自己提交一个 PR。结果在改的过程中，发现 `spring-alibaba-nacos-config` 中的配置类 `NacosConfigBootstrapConfiguration` 仅在 Test 代码中被调用过，除此以外没有任何代码注入这个 Configuration 类，这就会使得 NacosConfigProperties 类根本就不会生效，所以导致代码读取不到服务 yml 中的配置信息，那么就会出现服务无法读取 Nacos 配置中心配置的问题。

**Comment by 18670032796** [comment]
> 感觉不像是 srping cloud alibaba 的问题，sca 没有和数据库相关的代码部分。
> 
> 可以看看最新的 spring boot 版本和用的 orm 框架是不是兼容。或者能提供一个复现的最简例子，我们本地复现看看

这个是例子：
[springboot-alibaba.zip](https://github.com/user-attachments/files/17710770/springboot-alibaba.zip)

**Comment by 18670032796** [comment]
把 application.yml 改为  bootstrap.yml

**Comment by ldcsaa** [comment]
> 错误信息显示的是数据库问题，是因为服务启动时数据库相关内容加载的比较早。本质是因为无法读取到Nacos 的配置，读不到 Nacos 的配置所以首先抛出数据库连接问题。
> 
> 这个问题与 #3877 #3874 和 #3876 是同一个问题。2023.0.1.2 运行正常，升级到 2023.0.1.3 就会出问题。
> 
> 2023.0.1.3 目测最大的变化是提取出了一个配置模块。bootstrap 和 import 两种配置读取方式一直都是同时支持的，逻辑上不应该重构了代码就支持某一种了。个人猜测是 #3878 所致。

我也碰到同样问题，在创建数据库DataSource时，读取不到nacos的数据库配置信息。

**Comment by herodotus-ecosystem** [comment]
> > 错误信息显示的是数据库问题，是因为服务启动时数据库相关内容加载的比较早。本质是因为无法读取到Nacos 的配置，读不到 Nacos 的配置所以首先抛出数据库连接问题。
> > 这个问题与 #3877 #3874 和 #3876 是同一个问题。2023.0.1.2 运行正常，升级到 2023.0.1.3 就会出问题。
> > 2023.0.1.3 目测最大的变化是提取出了一个配置模块。bootstrap 和 import 两种配置读取方式一直都是同时支持的，逻辑上不应该重构了代码就支持某一种了。个人猜测是 #3878 所致。
> 
> 我也碰到同样问题，在创建数据库DataSource时，读取不到nacos的数据库配置信息。

可以临时改成 Import 方式，就可以用了。见：#3882

**Comment by troyzhxu** [comment]
在 Maven 仓库发现有 `2023.0.3.2` 版本,  升级到  `2023.0.3.2` 后，该问题依然存在。

**Comment by troyzhxu** [comment]
> 可以临时改成 Import 方式，就可以用了。见：#3882

把 `bootstrap.yml` 改成：

```yml
spring:
  application:
    name: xxxxxx
  cloud:
    nacos:
      config:
        file-extension: yml
      server-addr: x.x.x.x:xxxx
      username: xxxx
      password: xxxx
  config:
    import:
      - nacos:${spring.application.name}?refreshEnabled=true
```

确实就正常了。

以后版本, 这个配置项 `spring.config.import` 都是必须的了吗？
不添加这个配置项就不行了是吗？
