### ISSUE TITLE
新版本使用 import 加载配置时，spring.cloud.nacos.config相关配置属性只能在bootstrap才会生效，其他文件不生效

### ISSUE THREAD

**Issue by zxuanhong** [alibaba/spring-cloud-alibaba#3933]
**Describe the bug**
1. 新版本使用 import 加载配置时，spring.cloud.nacos.config相关配置只能在bootstrap才会生效，其他文件不生效
2. 比如我把以下配置弄在application.yml文件时，nacos 拉取不到**-dev.yml的配置文件，提示没有。但是放在bootstrap.yml 中能成功拉取到**-dev.yml 的配置文件
```yml
spring:
  cloud:
    nacos:
      config:
        namespace: dev
```
3. 具体视频如下

https://github.com/user-attachments/assets/125e7ebe-01e7-4abb-a03c-4a62789414ec

**Additional context**
system: mac
jdk: java21
spring-cloud-alibaba: 2023.0.3.2
