### ISSUE TITLE
spring cloud nacos 开启默认鉴权后，就拉取不到nacos上的配置了

### ISSUE THREAD

**Issue by xiaomizhou2** [alibaba/spring-cloud-alibaba#3934]
配置如下：
```yml
spring:
   config: 
      nacos: 
         username: nacos
         password: nacos
         config: 
           server-addr: 127.0.0.1:8848
           namespace: test
```
