### ISSUE TITLE
【2023.0.3.2】从 2023.0.1.2 升级至 2023.0.3.2 配置中心不读取配置文件

### ISSUE THREAD

**Issue by WangJincheng4869** [alibaba/spring-cloud-alibaba#3940]
我翻阅了不少 issues 得出的结论就是配置方式发上了变化（但是官方没有任何的声明），我有如下几个问题？

1. 为什么要抛弃原有的配置方式，而使用 `spring.config.import` 的方式？原来的配置模式是有什么弊端吗？
2. 为什么不兼容原始的配置方式？明明是一个小版本的升级，改动确如此之大。
3. 既然不兼容，为什么不将版本号提升为 `2024.0.0` 或者 `2023.1.0.0` 并做出明确标注？
4. 能否保留之前的配置方式，个人觉得新的方式在 `spring.config.import` 配置很乱，这种类 url 参数的模式并没有原来的对象形式好。

我看这个问题是在 `2023.0.1.3` 开始出现的，我暂时放弃升级，等待完善。

PS：这种做法显得太不专业了（其实我这个白嫖党没有资格说这个话，但是我还是要提一下）

**Comment by rowstop** [comment]
谁说不是呢，不支持就不支持吧，`spring-configuration-metadata.json`配置元数据里竟然还保留这些配置的信息，这不是误导人嘛

**Comment by rowstop** [comment]
[Nacos 配置中心进阶指南](https://sca.aliyun.com/docs/2023/user-guide/nacos/advanced-guide/?spm=5176.29160081.0.0.74805c726kaFmQ)
文档里保留着之前的配置方式，有没有这个可能：他们原是想支持的，但是出了bug

**Comment by lfift** [comment]
指定的spring.profiles.active无效导致读取不到配置，如果把nacos的相关配置放入application.yml就能够读取到配置。使用bootstrap也是一样的。。。

**Comment by lfift** [comment]
把spring.config.import的配置放入对应的application-${profile}.yml中就行了，应用启动时会先加载spring.config.import然后才是spring.profiles.active所以就导致了读取不到配置

**Comment by mushu1990** [comment]
就是，你的心不痛嘛！他娘的配置老不生效我都怀疑人生拉哈哈。

<img width="636" alt="Image" src="https://github.com/user-attachments/assets/e0745d99-1271-4853-93ff-9fd00ee78ab7" />

**Comment by qngl** [comment]
spring.config.import 在 spring boot 的启动过程中，触发的很早，另外 bootstrap.properties / yaml 被取消了，所以导致 以原有方式设置的 spring.cloud.nacos.x.x 相关值拿不到。这是出现问题的主要原因。所以只要让这些设置发生在 spring.config.import 之前，问题就可以解决。 
两个思路：
1. 把这下配置直接放在 spring.config.import 所在的 properties 文件里；
2. 自己定制一个 GenericApplicationListener，在 ApplicationEnvironmentPreparedEvent 事件里，把这些设置加载到 Environment 里就可以解决问题。

**Comment by jackspeed** [comment]
这算是bug 啥时候修复啊

**Comment by fenston** [comment]
> [Nacos 配置中心进阶指南](https://sca.aliyun.com/docs/2023/user-guide/nacos/advanced-guide/?spm=5176.29160081.0.0.74805c726kaFmQ) 文档里保留着之前的配置方式，有没有这个可能：他们原是想支持的，但是出了bug

应该不是，单纯的忘记删了，文档没人维护

**Comment by CarpCap** [comment]
我也遇到了这个问题，好像是依赖+nacos的bug导致的，  nacos有个9848端口，这个端口需要比8848端口大1000， 我设置好这个端口后就 读取配置 就没有问题了

**Comment by linqingyou** [comment]
github上官方的例子跑起来是没问题，我查下来，有两个问题需要注意：

1. 配置方式调整。原来依赖bootstrap的方式已经被放弃，其它配置方式的import集合的**文件一定不能有后缀**，否则会找不到文件，配置如下。另外2023.0.1.2原本会默认加载工程名的配置文件，在2023.0.3.2测试下来是以import的文件列表为准，看起来不会再加载nacos中的默认工程文件。
```
spring:
  config:
    import:
      - nacos:common-server
```
     
2.  要去除spring-cloud-starter-bootstrap依赖，这点很重要！！！我查了几天，最后才发现一旦工程依赖这个jar包，会默认启用bootstrap方式，最后在代码的RefreshEventListener的refresh属性会自动注入LegacyContextRefresher，这个refresh不会读取nacos中的配置更新。要让nacos配置更新能生效，refresh属性必须注入ConfigDataContextRefresher，这个refresh监听到context的refresh事件后，会主动去调用NacosConfigDataLoader的load加载nacos中配置属性，并生成propertySource设置到Environment对象中。去除spring-cloud-starter-bootstrap依赖，才会让ConfigDataContextRefresher自动注入到RefreshEventListener。

最后的代码示例:
```
spring:
  config:
    import:
      - nacos:common-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: xxxxxx
      discovery:
        heart-beat-interval: 2000
        heart-beat-timeout: 4000
        ip-delete-timeout: 4000
        failureToleranceEnabled: true
      config:
        fileExtension: yaml
```

官方样例代码：
https://github.com/alibaba/spring-cloud-alibaba/tree/2023.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example
