### ISSUE TITLE
v2023.0.1.3+ Configuring logging.level in bootstrap. yml file does not work 

### ISSUE THREAD

**Issue by herodotus-ecosystem** [alibaba/spring-cloud-alibaba#3995]
Spring Boot 提供了日志的配置机制，方便灵活修改日志的显示和输出。个人的配置如下所示

```yaml
spring:
  config:
    activate:
      on-profile: alibaba
    import:
      - nacos:herodotus-cloud-environment.yaml?group=${PROFILE:@profile@}
      - nacos:herodotus-cloud-platform.yaml?group=common
      - nacos:herodotus-cloud-database-${DATABASE:@database@}.yaml?group=common
      - nacos:herodotus-cloud-database.yaml?group=common
      - nacos:herodotus-cloud-redis.yaml?group=common
      - nacos:herodotus-cloud-cache.yaml?group=common
      - nacos:herodotus-cloud-rest.yaml?group=common
      - nacos:herodotus-cloud-kafka.yaml?group=common
      - nacos:herodotus-cloud-social.yaml?group=common
      - nacos:${spring.application.name}.yaml?group=service
  cloud:
    nacos:
      username: ${ALIBABA_USERNAME:@alibaba.username@}
      password: ${ALIBABA_PASSWORD:@alibaba.password@}
      config:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_CONFIG_SERVER_ADDR:@alibaba.config.server-addr@}
        file-extension: yaml
      discovery:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_DISCOVERY_SERVER_ADDR:@alibaba.discovery.server-addr@}
    sentinel:
      transport:
        port: 8719
        dashboard: ${ALIBABA_SENTINEL_SERVER_ADDR:@alibaba.sentinel.server-addr@}
#      datasource:
#        flow:
#          nacos:
#            server-addr: @alibaba.config.server-addr@
#            data-id: ${spring.application.name}-sentienl-flow.json
#            group-id: management
#            data-type: json
#            rule-type: flow

logging:
  file:
    name: logs/${spring.application.name}.log
  #  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=logs&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-spring.xml
  #  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=logs&dataId=logback-spring.xml
  level:
    root: info
    # 关闭不必要的日志
    org.reflections.Reflections: off
    com.alibaba.nacos.client: error
    com.alibaba.nacos.common.remote.client: error
    com.ulisesbocchio: error
    # 开发、调试需要的日志
    cn:
      herodotus: debug
    org.springframework.security: info
    org.springframework.web: debug
    com.alicp.jetcache: debug
    org.springframework.cloud.bus: info
    org.apache.kafka: off
```

## 问题

在 使用 SCA 2023.0.1.2 时，一切正常。通过在 bootstrap.yml 中 修改 `logging.level.<logger-name>=<level>` 就可以控制日志的输出和显示。

例如：将 org.springframework.security: info 修改为 org.springframework.security: debug 就会显示更多日志信息。

将 SCA 升级至 2023.0.1.3、2023.0.3.2 和 2023.0.3.3 以后， Spring Boot 的日志配置就完全失效。不管怎么修改 `logging.level.<logger-name>=<level>`  ，都无法改变日志的显示内容。

仅在修改 `logging.level.root` 值时，会显示不同级别的 Nacos 的相关的日志。

## 之前的问题

这个问题，之前就提出过了，一段时间后被系统自动关闭。相关问题：#3923 #3919

**Comment by herodotus-ecosystem** [comment]
已经找到问题所在，就是 `com.alibaba.cloud.nacos.client.NacosPropertySourceLocator` 注入的时机太靠后了。

在 Bootstrap 环境下，没有找到任何 `PropertySourceLocator`。Spring Cloud 就不会加载 Bootstrap.xml 中的相关配置了，特别是 logging.level。源代码如下：

```java
private void doInitialize(ConfigurableApplicationContext applicationContext) {
	List<PropertySource<?>> composite = new ArrayList<>();
	AnnotationAwareOrderComparator.sort(this.propertySourceLocators);
	boolean empty = true;
	ConfigurableEnvironment environment = applicationContext.getEnvironment();
        // PropertySourceLocator 注入时机滞后，这里 propertySourceLocators 的数量为 0
	for (PropertySourceLocator locator : this.propertySourceLocators) {
		Collection<PropertySource<?>> source = locator.locateCollection(environment);
		if (source == null || source.size() == 0) {
			continue;
		}
		List<PropertySource<?>> sourceList = new ArrayList<>();
		for (PropertySource<?> p : source) {
			if (p instanceof EnumerablePropertySource<?> enumerable) {
				sourceList.add(new BootstrapPropertySource<>(enumerable));
			}
			else {
				sourceList.add(new SimpleBootstrapPropertySource(p));
			}
		}
		logger.info("Located property source: " + sourceList);
		composite.addAll(sourceList);
		empty = false;
	}
        // 因为 propertySourceLocators  是空的，所以下面的操作都不会进行
       //  所以就不会 setLogLevels，导致日志不生效。
	if (!empty) {
		MutablePropertySources propertySources = environment.getPropertySources();
		String logConfig = environment.resolvePlaceholders("${logging.config:}");
		LogFile logFile = LogFile.get(environment);
		for (PropertySource<?> p : environment.getPropertySources()) {
			if (p.getName().startsWith(BOOTSTRAP_PROPERTY_SOURCE_NAME)) {
				propertySources.remove(p.getName());
			}
		}
		insertPropertySources(propertySources, composite);
		reinitializeLoggingSystem(environment);
		setLogLevels(applicationContext, environment);
		handleProfiles(environment);
	}
}
```

**Comment by herodotus-ecosystem** [comment]
2023.0.1.2 版本之所以没有问题，就是因为 `com.alibaba.cloud.nacos.client.NacosPropertySourceLocator` 在 Bootstrap 阶段就注入了。

**Comment by Yanzk** [comment]
经过验证，确实如此。我的问题也是这个原因 #4004 
坐等合并发版

**Comment by herodotus-ecosystem** [comment]
> 经过验证，确实如此。我的问题也是这个原因 [#4004](https://github.com/alibaba/spring-cloud-alibaba/issues/4004) 坐等合并发版

或者干脆放弃 Bootstrap 模式，就是把 bootstrap.yml 改成 application.yml

**Comment by Yanzk** [comment]
@herodotus-ecosystem 刚看了你提交的分支，没合并上。

**Comment by herodotus-ecosystem** [comment]
> [@herodotus-ecosystem](https://github.com/herodotus-ecosystem) 刚看了你提交的分支，没合并上。

规范性校验问题：'org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean' should be separated from previous imports. [ImportOrder] 必须空一行。

**Comment by herodotus-ecosystem** [comment]
> [@herodotus-ecosystem](https://github.com/herodotus-ecosystem) 刚看了你提交的分支，没合并上。

SCA 2023.0.1.3 以及之后的版本变化，一方面是为了提取共用模块；另一方面是不打算再兼容 Bootstrap 模式。

因为，确实是 Boostrap 模式是兼容的模式，是 Spring 本身也已经不再推荐使用。

所以，现在最好的办法就是：

1. 把现在所有的 Nacos 配置，全部改成 `spring.config.import` 的方式
2. 把服务中的 Bootstrap.yml 全部改成 application.yml

这样的话`spring-cloud-starter-boostrap` 也不需要依赖了。这样操作之后，现在的 SCA 2023.0.3.3 就直接可以用，不会有任何问题。

这两天我也仔细看了看。我提交的 PR #4069  也仅是兼容老用户 Bootstrap 模式的补救措施。与 SCA 新版本的用法不符，也不符合 Spring 的规范。

> 因为 Bootstrap 模式还是需要依赖于 `spring.factories` 配置文件，但这个文件已经不是 Spring Boot 3.x 标准用法了，由此可见 不推荐 Bootstrap 模式是对的，早晚要被淘汰。特别是今年的年底要发布 Spring Boot 4.X 了。@Yanzk

**Comment by herohakcker** [comment]
遇到同样的问题

**Comment by NoBugBoy** [comment]
> application.yml

SCA 2023.0.3.3
NACOS 3.0.0
改为application.yml完全无法启动
使用bootstrap 只会报错 
 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - Attempted to append to non started appender [NAMING_LOG_FILE].

**Comment by herodotus-ecosystem** [comment]
重新提交了一个 PR，见 #4069

**Comment by herodotus-ecosystem** [comment]
> > application.yml
> 
> SCA 2023.0.3.3 NACOS 3.0.0 改为application.yml完全无法启动 使用bootstrap 只会报错 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - Attempted to append to non started appender [NAMING_LOG_FILE].

看上面这个解决办法，依赖问题：#4004

**Comment by herohakcker** [comment]
嗯，是的，就是要排除日志才可以



发自我的iPhone


------------------ Original ------------------
From: 码匠君 ***@***.***&gt;
Date: Thu,Sep 25,2025 5:07 PM
To: alibaba/spring-cloud-alibaba ***@***.***&gt;
Cc: herohakcker ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [alibaba/spring-cloud-alibaba] v2023.0.1.3+ Configuringlogging.level in bootstrap. yml file does not work  (Issue #3995)



herodotus-ecosystem left a comment (alibaba/spring-cloud-alibaba#3995)
   
application.yml
  
SCA 2023.0.3.3 NACOS 3.0.0 改为application.yml完全无法启动 使用bootstrap 只会报错 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - Attempted to append to non started appender [NAMING_LOG_FILE].
  
看上面这个解决办法，依赖问题：#4004

**Comment by uuuyuqi** [comment]
我本地使用 spring-cloud-alibaba 版本为 2023.0.1.3，尝试复现了一下这个问题，但是结果没有复现（bootstrap.yml 中的日志配置可以正常生效）。可以帮忙看一下是哪里的配置没满足吗 @herodotus-ecosystem 

### 以下是我的项目配置
boostrap.yml 内容：
```yaml
logging:
  level:
    root: warn
    org.springframework.web: debug

spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:sc-A.yaml?refreshEnabled=true
  cloud:
    nacos:
      config:
        serverAddr: 127.0.0.1:8848
```

application-dev.yml 内容：
```yaml
server:
  port: 20001

spring:
  application:
    name: sc-A

```

入口启动类：
```java
package me.qh;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class Main {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(Main.class, args);
        System.out.println(context.getEnvironment().getProperty("k1"));
    }
}
```

测试 Controller：
```java
package me.qh.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.commons.util.InetUtils;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AController {
    @Autowired
    InetUtils inetUtils;

    @Value("${k1}")
    String k1;

    @RequestMapping("/a")
    public String a() {
        System.out.println(k1);
        return "A" + "[" + inetUtils.findFirstNonLoopbackAddress().getHostAddress() + "]";
    }
}

```

pom 文件关键配置：
```xml
  <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>

        <spring-boot.version>3.2.4</spring-boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.3</spring-cloud-alibaba.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
```
