### ISSUE TITLE
nacos config autoRefresh wrong datas bug?

### ISSUE THREAD

**Issue by hello-zhengzq** [alibaba/spring-cloud-alibaba#731]
**Which Component**
Nacos Dynamic Configuration Service

**Describe the bug**
while i using the Dynamic Configuration Service for autoRefreshing data, some datas seemed not be refreshed correctly.

**To Reproduce**
1. nacos yml format configurations as follow:
```
book:
  categories:
    CAT: description bla bla bla
    DOG: description bla bla bla
```

java code like:
```
@Component
@ConfigurationProperties(prefix = "book")
@Data
public class Config {
	private HashMap<String, String> categories;
}
```

so far everything is is going well，categories contains CAT and DOG.

2. then i modified the configuration as follow:
```
book:
  categories:
    CAT: description bla bla bla
    PANDA: description bla bla bla
```

expect result is categories contains CAT and PANDA, but result is CAT、DOG and PANDA.

**Screenshots**
-

**Additional context**
environment as follow:
springcloud Greenwich.SR2
springcloud alibaba 0.9.0.RELEASE
NACOS DASHBOARD v1.0.0
