### ISSUE TITLE
如何在Nacos配置中心中拉取不同的配置文件？（How to pull different configuration files in the Nacos configuration center?）

### ISSUE THREAD

**Issue by GuoxinL** [alibaba/spring-cloud-alibaba#810]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

问题：
Question:
我尝试将spring boot项目接入到nacos配置中心中，并且已经成功将`yaml`接入到Nacos配置中心，请问该如何在Nacos配置中心中拉取不同的配置文件？
I tried to connect the spring boot project to the nacos configuration center, and have successfully connected 'yaml' to the nacos configuration center. May I ask how to pull different configuration files in the nacos configuration center?

eg: pkcs8_rsa_private_key.pem
这是非对称加密的钥匙，如何将这个文件顺利的从配置中心拉去下来？
This is an asymmetric encryption key, how to smoothly pull this file down from the configuration center?

bootstrap.yml
```yml
spring:
  application:
    name: xxx
  cloud:
    nacos:
      config:
        namespace: 1fe6cb84-a57f-497e-b5db-9df32e56d526
        server-addr: localhost:8848
        file-extension: yaml
        shared-dataids: pkcs8_rsa_private_key.pem,mongo.yaml,mysql.yaml,redis.yaml,xxl-job.yaml,mybatis-plus.yaml,actuator.yaml,mybatis-plus.yaml
        refreshable-dataids: pkcs8_rsa_private_key.pem,mongo.yaml,mysql.yaml,redis.yaml,xxl-job.yaml,mybatis-plus.yaml,actuator.yaml,mybatis-plus.yaml
      discovery:
        server-addr: localhost:8848
```
```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>0.2.1.RELEASE</version>
        </dependency>
```
Nacos version: NACOS1.0.0
Nacos SDK and version: spring-cloud-starter-alibaba-nacos-config:0.2.1.RELEASE

**Comment by 1346735074** [comment]
Hello, it can be configured below
NacosConfigProperties->extConfig
```
spring:
  cloud:
    nacos:
      config:
        server-addr: '127.0.0.1:8848'      # 配置中心地址
        file-extension: 'yml'                   # 使用格式
        namespace: 'ed5131f7-f8cf-4369-a713-c87f8bbc4286'   # 分组（dev，test等）
 
 
        # 用于多配置项 （比如读取该项目的主配置之后，再读取一个单独的配置）
        ext-config[0]:                      # 数组形式                     
          data-id: 'public.yml'             # 配置名称
          group: 'DEFAULT_GROUP'            # 分组名称
          refresh: true                     # 是否动态刷新
```
