### ISSUE TITLE
Design about Sentinel Dashborad

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#842]
今天有个朋友反馈，使用：

```
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
      <version>2.1.0.RELEASE</version>
    </dependency>
```

之后，就会有这样的问题：

当 Sentinel Dashborad 挂掉的话，也会导致应用的健康检查状态变成 `DOWN` ，这是很不合理的。健康检查，检查的是应用的资源，主要是用来及早的解决应用的问题。如果用的是Consul作为注册中心，而Sentinel Dashborad挂掉的话，那应用都调不起来了……

定位了下源码，目前只能使用如下配置解决问题。

```yaml
management:
  health:
    sentinel:
      enabled: false
```

也就是关闭掉Sentinel的检查。

建议：额外添加一个配置，控制是否检查Dashboard是否可连接的状态，并且默认应该设置为false。
