### ISSUE TITLE
当没有服务提供者时，设置dubbo.consumer.check=fasle启动消费者后再启动服务提供者，会报找不到服务提供者

### ISSUE THREAD

**Issue by Tank-zhu** [alibaba/spring-cloud-alibaba#874]
# consumer   bootstrap.yaml
```
spring:
  application:
    name: dubbo-nacos-consumer
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: 172.16.249.223:8848
        file-extension: yaml
      discovery:
        server-addr: 172.16.249.223:8848
        enabled: true
        register-enabled: true
ribbon:
  nacos:
    enabled: true

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: nacos
  consumer:
    check: false
```
# 服务消费者调用代码
```
public class ConsumeWeb {

    private String key;


    @Autowired
    ConsumeService consumeService;

    @RequestMapping(value = "/say/{name}")
    public String say(@PathVariable("name") String name){
        return consumeService.initData(name,key);
    }
}

@Service
public class ConsumeService {

    @Reference
    ProviderService providerService;


    public String initData(String name,String key){
        return "调用完成" + providerService.sayHello(name)+"  "+key;
    }
}
```
# provider  bootstrap.yaml

```
dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.tank.dubbo.provider.dubbonacosprovider.provider
  protocols:
    dubbo:
      name: dubbo
      port: -1
  cloud:
    subscribed-services: ""
spring:
  application:
    name: nacos
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: 172.16.249.223:8848
        file-extension: yaml
      discovery:
        server-addr: 172.16.249.223:8848
        enabled: true
        register-enabled: true
```
#服务提供者代码
```
@Service(protocol = "dubbo")
public class ProviderServiceImpl implements ProviderService {
    @Autowired
    ChannelConfigServiceImpl channelConfigService;

    @Override
    public String sayHello(String name) {
        channelConfigService.list().forEach(e -> System.out.println(e.toString()));
        return "***** OH ， My God!~~~~" + name +"   数据库返回数据"+
                 channelConfigService.list().get(0).toString() ;

    }
```

# 当没有服务提供者时，设置dubbo.consumer.check=fasle启动消费者后再启动服务提供者，会报找不到服务提供者
![image](https://user-images.githubusercontent.com/10337065/63514249-c49dac80-c51a-11e9-8221-ccd66f368c48.png)

# 如果先启动服务提供者再起到服务消费者，请求正常
![image](https://user-images.githubusercontent.com/10337065/63514300-e4cd6b80-c51a-11e9-8b9d-9a4896e4daa6.png)

# 有没有办法可以解决这个问题呢？
