### ISSUE TITLE
连接RoketMQ错误提示优化

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#977]
有个朋友连接RocketMQ集群，使用如下配置：
```yaml
cloud:
  stream:
    rocketmq:
      binder:
        # 地址列表元素之间用;分隔
        name-server: 39.100.226.179:9876,39.100.78.47:9876
```
name server地址列表元素之间应该用;分隔，但是这哥们使用的是, 
启动没有报错、消费消息时，才报异常。而且报的异常很难让人联想到是地址配置有问题。

因此，我个人认为现有地址列表的设计，对新手不太友好。建议的优化方案：
方案1：org.springframework.cloud.stream.binder.rocketmq.properties.RocketMQBinderConfigurationProperties#nameServer 上配置个正则，不允许含有逗号；并且在RocketMQBinderConfigurationProperties类上弄个@Validated。

方案2：
生产/消费消息时，优化一下错误提示，打印出Name Server地址（成本相对更高）。
